package com.cq.maintenance.sla;

import static org.junit.jupiter.api.Assertions.*;import static org.mockito.ArgumentMatchers.*;import static org.mockito.Mockito.*;
import com.cq.maintenance.common.exception.BusinessException;import com.cq.maintenance.notification.service.NotificationService;import com.cq.maintenance.repair.entity.RepairPriority;import com.cq.maintenance.sla.dto.*;import com.cq.maintenance.sla.entity.*;import com.cq.maintenance.sla.mapper.SlaMapper;import com.cq.maintenance.sla.service.SlaService;import com.cq.maintenance.sla.vo.*;import com.cq.maintenance.workorder.mapper.WorkOrderMapper.WorkOrderDataScope;import com.cq.maintenance.workorder.service.WorkOrderScopeService;import java.time.LocalDateTime;import java.util.*;import org.junit.jupiter.api.*;

class SlaServiceTest {
    SlaMapper mapper;NotificationService notifications;WorkOrderScopeService scopes;SlaService service;LocalDateTime now=LocalDateTime.of(2026,9,14,12,0);
    @BeforeEach void setup(){mapper=mock(SlaMapper.class);notifications=mock(NotificationService.class);scopes=mock(WorkOrderScopeService.class);service=new SlaService(mapper,notifications,scopes);when(mapper.findResponseTimeouts(any())).thenReturn(List.of());when(mapper.findResolveTimeouts(any())).thenReturn(List.of());}
    SlaRule rule(){SlaRule r=new SlaRule();r.setId(3L);r.setPriority(RepairPriority.URGENT);r.setResponseMinutes(30);r.setResolveMinutes(240);r.setEnabled(true);return r;}
    SlaMonitorRow row(SlaEventType type,Long receiver){return new SlaMonitorRow(7L,"WO7",3L,type,now.minusMinutes(1),receiver,receiver==null?null:"主管");}
    @Test void bindsEnabledPriorityRule(){when(mapper.findEnabledRule(RepairPriority.URGENT)).thenReturn(rule());when(mapper.bindRule(7L,3L,30,240)).thenReturn(1);service.bindRepairOrder(7L,RepairPriority.URGENT);verify(mapper).bindRule(7L,3L,30,240);}
    @Test void missingRuleRejectsRepairCreation(){assertThrows(BusinessException.class,()->service.bindRepairOrder(7L,RepairPriority.NORMAL));}
    @Test void duplicateBindingIsRejected(){when(mapper.findEnabledRule(RepairPriority.URGENT)).thenReturn(rule());assertThrows(BusinessException.class,()->service.bindRepairOrder(7L,RepairPriority.URGENT));}
    @Test void responseCannotExceedResolve(){assertThrows(BusinessException.class,()->service.updateRule(3L,new SlaRuleUpdateRequest(60,30,true)));}
    @Test void missingRuleCannotUpdate(){assertThrows(BusinessException.class,()->service.updateRule(8L,new SlaRuleUpdateRequest(30,60,true)));}
    @Test void validRuleCanUpdate(){when(mapper.updateRule(3L,30,60,true)).thenReturn(1);service.updateRule(3L,new SlaRuleUpdateRequest(30,60,true));}
    @Test void responseTimeoutCreatesEventAndMessage(){when(mapper.findResponseTimeouts(now)).thenReturn(List.of(row(SlaEventType.RESPONSE_TIMEOUT,9L)));when(mapper.insertEvent(any())).thenAnswer(i->{((SlaEvent)i.getArgument(0)).setId(11L);return 1;});when(notifications.createSla(anyLong(),anyLong(),anyString(),anyString())).thenReturn(21L);assertEquals(1,service.scan(now));verify(mapper).linkMessage(11L,21L);}
    @Test void resolveTimeoutCreatesEventAndMessage(){when(mapper.findResolveTimeouts(now)).thenReturn(List.of(row(SlaEventType.RESOLVE_TIMEOUT,9L)));when(mapper.insertEvent(any())).thenAnswer(i->{((SlaEvent)i.getArgument(0)).setId(12L);return 1;});when(notifications.createSla(anyLong(),anyLong(),anyString(),anyString())).thenReturn(22L);assertEquals(1,service.scan(now));verify(notifications).createSla(eq(9L),eq(7L),contains("解决"),contains("WO7"));}
    @Test void repeatedScanDoesNotRepeatMessage(){when(mapper.findResponseTimeouts(now)).thenReturn(List.of(row(SlaEventType.RESPONSE_TIMEOUT,9L)));when(mapper.insertEvent(any())).thenReturn(0);assertEquals(0,service.scan(now));verifyNoInteractions(notifications);}
    @Test void missingEscalationTargetKeepsEventSafely(){when(mapper.findResponseTimeouts(now)).thenReturn(List.of(row(SlaEventType.RESPONSE_TIMEOUT,null)));when(mapper.insertEvent(any())).thenReturn(1);assertEquals(1,service.scan(now));verifyNoInteractions(notifications);}
    @Test void bothTimeoutTypesCanBeCreatedOnce(){when(mapper.findResponseTimeouts(now)).thenReturn(List.of(row(SlaEventType.RESPONSE_TIMEOUT,null)));when(mapper.findResolveTimeouts(now)).thenReturn(List.of(row(SlaEventType.RESOLVE_TIMEOUT,null)));when(mapper.insertEvent(any())).thenReturn(1);assertEquals(2,service.scan(now));}
    @Test void oneFaultyItemDoesNotStopLaterItems(){when(mapper.findResponseTimeouts(now)).thenReturn(List.of(row(SlaEventType.RESPONSE_TIMEOUT,null),new SlaMonitorRow(8L,"WO8",3L,SlaEventType.RESPONSE_TIMEOUT,now,null,null)));when(mapper.insertEvent(any())).thenThrow(new RuntimeException("one")).thenReturn(1);assertEquals(1,service.scan(now));}
    @Test void eventPageUsesCurrentScope(){SlaEventQuery q=new SlaEventQuery();WorkOrderDataScope scope=new WorkOrderDataScope(false,"SUPERVISOR",1L,4L,List.of(3L));when(scopes.current()).thenReturn(scope);service.events(q);verify(mapper).findEventPage(q,scope);verify(mapper).countEvents(q,scope);}
    @Test void invisibleEventCannotBeHandled(){when(scopes.current()).thenReturn(new WorkOrderDataScope(false,"SUPERVISOR",1L,4L,List.of()));assertThrows(BusinessException.class,()->service.handle(2L));}
    @Test void eventCanBeHandledOnce(){var scope=new WorkOrderDataScope(true,"ALL",1L,null,List.of());when(scopes.current()).thenReturn(scope);when(mapper.countEventVisible(2L,scope)).thenReturn(1L);when(mapper.handle(2L)).thenReturn(1);service.handle(2L);}
    @Test void duplicateHandleIsRejected(){var scope=new WorkOrderDataScope(true,"ALL",1L,null,List.of());when(scopes.current()).thenReturn(scope);when(mapper.countEventVisible(2L,scope)).thenReturn(1L);assertThrows(BusinessException.class,()->service.handle(2L));}
}
