package com.cq.maintenance.system.service;
import com.cq.maintenance.equipment.vo.ImportResultVO;
import com.cq.maintenance.equipment.vo.ImportResultVO.RowError;
import com.cq.maintenance.system.dto.UserCreateRequest;
import com.cq.maintenance.system.vo.UserMetadataVO;
import java.io.*;import java.util.*;import java.util.function.Function;import java.util.stream.Collectors;
import org.apache.poi.ss.usermodel.*;import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.springframework.stereotype.Service;import org.springframework.web.multipart.MultipartFile;
@Service public class UserExcelService {private static final String[] HEADERS={"账号*","初始密码*","姓名*","手机号","邮箱","岗位","角色编码*（多个用逗号）","技能编码（多个用逗号）"};private final UserManagementService users;public UserExcelService(UserManagementService users){this.users=users;}
 public byte[] template(){try(XSSFWorkbook book=new XSSFWorkbook();ByteArrayOutputStream out=new ByteArrayOutputStream()){Sheet sheet=book.createSheet("用户导入");Row header=sheet.createRow(0);for(int i=0;i<HEADERS.length;i++){header.createCell(i).setCellValue(HEADERS[i]);sheet.setColumnWidth(i,i<3?18*256:24*256);}Row sample=sheet.createRow(1);String[] values={"engineer02","DevOnly@123","演示工程师二","","","维修工程师","ENGINEER","MECHANICAL"};for(int i=0;i<values.length;i++)sample.createCell(i).setCellValue(values[i]);book.write(out);return out.toByteArray();}catch(IOException ex){throw new IllegalStateException("用户Excel模板生成失败",ex);}}
 public ImportResultVO importFile(MultipartFile file){if(file==null||file.isEmpty())return new ImportResultVO(0,0,1,List.of(new RowError(0,"","请选择Excel文件")));int total=0,success=0;List<RowError> errors=new ArrayList<>();UserMetadataVO meta=users.metadata();Map<String,Long> roles=meta.roles().stream().collect(Collectors.toMap(UserMetadataVO.Option::code,UserMetadataVO.Option::id));Map<String,Long> skills=meta.skills().stream().collect(Collectors.toMap(UserMetadataVO.Option::code,UserMetadataVO.Option::id));try(InputStream in=file.getInputStream();Workbook book=WorkbookFactory.create(in)){Sheet sheet=book.getSheetAt(0);for(int i=1;i<=sheet.getLastRowNum();i++){Row row=sheet.getRow(i);if(row==null||text(row,0).isBlank())continue;total++;String username=text(row,0);try{List<Long> roleIds=ids(text(row,6),roles,true,"角色");List<Long> skillIds=ids(text(row,7),skills,false,"技能");users.create(new UserCreateRequest(username,text(row,1),text(row,2),nullable(row,3),nullable(row,4),nullable(row,5),null,null,roleIds,skillIds));success++;}catch(Exception ex){errors.add(new RowError(i+1,username,root(ex)));}}}catch(Exception ex){errors.add(new RowError(0,"","文件格式错误："+root(ex)));}return new ImportResultVO(total,success,errors.size(),List.copyOf(errors));}
 private List<Long> ids(String raw,Map<String,Long> options,boolean required,String label){if(raw.isBlank()){if(required)throw new IllegalArgumentException(label+"编码不能为空");return List.of();}List<Long> result=new ArrayList<>();for(String code:raw.split("[,，]")){Long id=options.get(code.trim().toUpperCase(Locale.ROOT));if(id==null)throw new IllegalArgumentException(label+"编码不存在："+code.trim());result.add(id);}return result.stream().distinct().toList();}
 private String text(Row row,int index){Cell c=row.getCell(index,Row.MissingCellPolicy.RETURN_BLANK_AS_NULL);if(c==null)return"";return new DataFormatter().formatCellValue(c).trim();}private String nullable(Row r,int i){String v=text(r,i);return v.isBlank()?null:v;}private String root(Throwable ex){Throwable t=ex;while(t.getCause()!=null)t=t.getCause();return t.getMessage()==null?t.getClass().getSimpleName():t.getMessage();}
}
