package com.cq.maintenance.workorder;

import static org.junit.jupiter.api.Assertions.*;import static org.mockito.ArgumentMatchers.*;import static org.mockito.Mockito.*;
import com.cq.maintenance.common.exception.BusinessException;import com.cq.maintenance.equipment.entity.EquipmentStatus;import com.cq.maintenance.equipment.service.EquipmentStateService;import com.cq.maintenance.inventory.service.InventoryService;import com.cq.maintenance.maintenance.service.MaintenanceExecutionService;import com.cq.maintenance.security.LoginUser;import com.cq.maintenance.workorder.dto.*;import com.cq.maintenance.workorder.entity.*;import com.cq.maintenance.workorder.mapper.WorkOrderMapper;import com.cq.maintenance.workorder.service.*;import com.cq.maintenance.workorder.vo.WorkOrderListVO;import java.math.BigDecimal;import java.util.List;import org.junit.jupiter.api.*;import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;import org.springframework.security.core.context.SecurityContextHolder;

class WorkOrderServiceTest {
    WorkOrderMapper mapper;WorkOrderScopeService scopes;WorkOrderStateService states;EquipmentStateService equipmentStates;InventoryService inventory;MaintenanceExecutionService maintenance;WorkOrderService service;
    @BeforeEach void setUp(){mapper=mock(WorkOrderMapper.class);scopes=mock(WorkOrderScopeService.class);states=mock(WorkOrderStateService.class);equipmentStates=mock(EquipmentStateService.class);inventory=mock(InventoryService.class);maintenance=mock(MaintenanceExecutionService.class);service=new WorkOrderService(mapper,scopes,states,equipmentStates,inventory,maintenance);LoginUser u=new LoginUser(7L,"engineer","工程师","ENABLED",List.of("ENGINEER"),List.of(),List.of(3L),4L,List.of());SecurityContextHolder.getContext().setAuthentication(UsernamePasswordAuthenticationToken.authenticated(u,null,List.of()));}
    @AfterEach void clear(){SecurityContextHolder.clearContext();}
    WorkOrder order(WorkOrderStatus status){WorkOrder o=new WorkOrder();o.setId(1L);o.setWorkOrderNo("WO1");o.setWorkOrderType(WorkOrderType.REPAIR);o.setRepairRequestId(2L);o.setEquipmentId(5L);o.setAssignedEngineerId(7L);o.setStatus(status);when(mapper.lockWorkOrder(1L)).thenReturn(o);return o;}
    WorkOrderListVO summary(Long reporter){WorkOrderListVO v=new WorkOrderListVO(1L,"WO1",WorkOrderType.REPAIR,2L,"RR1",5L,"E1","设备",4L,"车间",null,WorkOrderStatus.PENDING_ACCEPT,reporter,"报修人",7L,"工程师",3L,"班组",null,null,null,null,null,null,0,null,null,null,null);when(mapper.findWorkOrderSummary(1L)).thenReturn(v);return v;}
    RepairRecord complete(){RepairRecord r=new RepairRecord();r.setInspectionProcess("检查");r.setRootCause("磨损");r.setRepairAction("更换");r.setRepairResult("正常");r.setRepairable(true);r.setLaborHours(BigDecimal.ONE);r.setDowntimeMinutes(30);return r;}
    RepairRecordRequest recordInput(){return new RepairRecordRequest("检查","磨损","更换","正常",BigDecimal.ONE,30,true);}
    @Test void assignedEngineerCanStartAndEquipmentRepairs(){order(WorkOrderStatus.ASSIGNED);service.start(1L);verify(states).transition(any(),eq(WorkOrderStatus.PROCESSING),eq("START"),anyString(),eq(7L));verify(equipmentStates).transition(eq(5L),eq(EquipmentStatus.REPAIRING),contains("WO1"),eq("WORK_ORDER"),eq(1L),eq(7L));}
    @Test void unassignedEngineerIsRejected(){order(WorkOrderStatus.ASSIGNED);doThrow(new BusinessException(com.cq.maintenance.common.exception.ErrorCode.DATA_FORBIDDEN)).when(scopes).assertAssignedEngineer(any());assertThrows(BusinessException.class,()->service.start(1L));verify(equipmentStates,never()).transition(anyLong(),any(),anyString(),anyString(),anyLong(),anyLong());}
    @Test void processingEngineerCanCreateRepairRecord(){order(WorkOrderStatus.PROCESSING);when(mapper.findRepairRecord(1L)).thenReturn(null);service.saveRepairRecord(1L,recordInput());verify(mapper).insertRepairRecord(argThat(r->r.getCreatedBy().equals(7L)&&r.getRootCause().equals("磨损")));}
    @Test void completedOrderCannotEditRecord(){order(WorkOrderStatus.COMPLETED);assertThrows(BusinessException.class,()->service.saveRepairRecord(1L,recordInput()));}
    @Test void incompleteRecordCannotSubmit(){order(WorkOrderStatus.PROCESSING);when(mapper.findRepairRecord(1L)).thenReturn(null);assertThrows(BusinessException.class,()->service.submitAcceptance(1L));}
    @Test void completeRecordCanSubmit(){order(WorkOrderStatus.PROCESSING);when(mapper.findRepairRecord(1L)).thenReturn(complete());service.submitAcceptance(1L);verify(states).transition(any(),eq(WorkOrderStatus.PENDING_ACCEPT),eq("SUBMIT"),anyString(),eq(7L));}
    @Test void acceptancePassCompletesAndRestoresEquipment(){summary(9L);order(WorkOrderStatus.PENDING_ACCEPT);when(mapper.findRepairRecord(1L)).thenReturn(complete());service.pass(1L,new AcceptanceRequest("试运行正常"));verify(states).transition(any(),eq(WorkOrderStatus.COMPLETED),eq("ACCEPT_PASS"),eq("试运行正常"),eq(7L));verify(equipmentStates).transition(eq(5L),eq(EquipmentStatus.RUNNING),contains("WO1"),eq("WORK_ORDER"),eq(1L),eq(7L));}
    @Test void acceptanceReturnKeepsEquipmentRepairing(){summary(9L);order(WorkOrderStatus.PENDING_ACCEPT);service.reject(1L,new ReasonRequest("仍有异响"));verify(states).transition(any(),eq(WorkOrderStatus.PROCESSING),eq("ACCEPT_RETURN"),eq("仍有异响"),eq(7L));verifyNoInteractions(equipmentStates);}
    @Test void cancellingLastOrderDisposesEquipment(){order(WorkOrderStatus.PENDING_ASSIGN);when(mapper.cancelRepairRequest(2L,"误报")).thenReturn(1);when(mapper.countActiveRepairOrders(5L,1L)).thenReturn(0L);service.cancel(1L,new CancelWorkOrderRequest("误报",EquipmentStatus.RUNNING));verify(equipmentStates).cancelWorkOrder(5L,EquipmentStatus.RUNNING,"误报",1L,7L);}
    @Test void cancellingOneOfSeveralOrdersDoesNotRestoreEquipment(){order(WorkOrderStatus.ASSIGNED);when(mapper.cancelRepairRequest(2L,"重复")).thenReturn(1);when(mapper.countActiveRepairOrders(5L,1L)).thenReturn(1L);service.cancel(1L,new CancelWorkOrderRequest("重复",EquipmentStatus.RUNNING));verifyNoInteractions(equipmentStates);}
    @Test void maintenanceStartDoesNotChangeEquipmentState(){WorkOrder o=order(WorkOrderStatus.ASSIGNED);o.setWorkOrderType(WorkOrderType.MAINTENANCE);service.start(1L);verifyNoInteractions(equipmentStates);verify(states).transition(any(),eq(WorkOrderStatus.PROCESSING),eq("START"),contains("保养"),eq(7L));}
    @Test void maintenanceCannotWriteRepairRecord(){WorkOrder o=order(WorkOrderStatus.PROCESSING);o.setWorkOrderType(WorkOrderType.MAINTENANCE);assertThrows(BusinessException.class,()->service.saveRepairRecord(1L,recordInput()));}
    @Test void completeMaintenanceCanSubmit(){WorkOrder o=order(WorkOrderStatus.PROCESSING);o.setWorkOrderType(WorkOrderType.MAINTENANCE);service.submitAcceptance(1L);verify(maintenance).assertComplete(1L);verify(states).transition(any(),eq(WorkOrderStatus.PENDING_ACCEPT),eq("SUBMIT"),contains("保养"),eq(7L));}
    @Test void maintenanceAcceptanceDoesNotForceEquipmentRunning(){summary(9L);WorkOrder o=order(WorkOrderStatus.PENDING_ACCEPT);o.setWorkOrderType(WorkOrderType.MAINTENANCE);service.pass(1L,new AcceptanceRequest("保养完成"));verify(maintenance).assertComplete(1L);verifyNoInteractions(equipmentStates);}
}
