<script setup lang="ts">
import { onMounted, reactive, shallowRef } from 'vue'
import { useRouter } from 'vue-router'
import { ElMessage } from 'element-plus'
import * as api from '../../api/workorder'
import { priorityLabel, priorityType, repairPriorities, workOrderStatuses, workOrderStatusLabel, workOrderStatusType } from '../../utils/workOrderStatus'
const router=useRouter();const loading=shallowRef(false);const records=shallowRef<any[]>([]);const total=shallowRef(0)
const query=reactive<any>({workOrderNo:'',equipmentKeyword:'',status:null,priority:null,page:1,size:10})
async function load(){loading.value=true;try{const response=await api.page(query);records.value=response.data.records;total.value=response.data.total}catch(e:any){ElMessage.error(e.response?.data?.message||'工单加载失败')}finally{loading.value=false}}
function search(){query.page=1;load()}function reset(){Object.assign(query,{workOrderNo:'',equipmentKeyword:'',status:null,priority:null,page:1,size:10});load()}
onMounted(load)
</script>
<template><section class="module-page"><header class="module-header"><div><p class="eyebrow">MAINTENANCE WORKFLOW</p><h1>维修工单</h1><p>按角色数据范围查看派单、维修与验收进度。</p></div></header><el-card shadow="never" class="filter-card"><el-form inline><el-form-item label="工单编号"><el-input v-model="query.workOrderNo" clearable @keyup.enter="search"/></el-form-item><el-form-item label="设备"><el-input v-model="query.equipmentKeyword" clearable placeholder="编号/名称" @keyup.enter="search"/></el-form-item><el-form-item label="状态"><el-select v-model="query.status" clearable><el-option v-for="(item,key) in workOrderStatuses" :key="key" :label="item.label" :value="key"/></el-select></el-form-item><el-form-item label="等级"><el-select v-model="query.priority" clearable><el-option v-for="(item,key) in repairPriorities" :key="key" :label="item.label" :value="key"/></el-select></el-form-item><el-form-item class="filter-actions"><el-button type="primary" :loading="loading" @click="search">查询</el-button><el-button @click="reset">重置</el-button></el-form-item></el-form></el-card><el-card shadow="never"><template #header><div class="card-title"><strong>工单列表</strong><small>状态是当前业务进度，进入详情可查看完整流转</small></div></template><el-table v-loading="loading" :data="records" stripe><template #empty><el-empty description="暂无维修工单" :image-size="72"/></template><el-table-column prop="workOrderNo" label="工单编号" min-width="190" show-overflow-tooltip/><el-table-column label="设备" min-width="175"><template #default="{row}"><span class="table-primary">{{row.equipmentName}}</span><small class="table-subtitle">{{row.equipmentNo}}</small></template></el-table-column><el-table-column prop="workshopName" label="位置" width="112" show-overflow-tooltip/><el-table-column label="等级" width="84"><template #default="{row}"><el-tag :type="priorityType(row.priority)" effect="plain">{{priorityLabel(row.priority)}}</el-tag></template></el-table-column><el-table-column label="状态" width="105"><template #default="{row}"><el-tag :type="workOrderStatusType(row.status)">{{workOrderStatusLabel(row.status)}}</el-tag></template></el-table-column><el-table-column prop="assignedEngineerName" label="当前负责人" width="115" show-overflow-tooltip><template #default="{row}">{{row.assignedEngineerName||'待派单'}}</template></el-table-column><el-table-column prop="createdAt" label="报修时间" width="168"/><el-table-column label="操作" width="96" fixed="right"><template #default="{row}"><el-button link type="primary" @click="router.push(`/work-orders/${row.id}`)">查看详情</el-button></template></el-table-column></el-table><div class="pagination-row"><el-pagination v-model:current-page="query.page" v-model:page-size="query.size" :total="total" layout="total, sizes, prev, pager, next" @change="load"/></div></el-card></section></template>
