<script setup lang="ts">
import { computed, nextTick, onMounted, reactive, shallowRef } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { ElMessage, ElMessageBox } from 'element-plus'
import * as api from '../../api/workorder'
import { useAuthStore } from '../../stores/auth'
import { priorityLabel, priorityType, workOrderStatusLabel, workOrderStatusType } from '../../utils/workOrderStatus'
const route=useRoute();const router=useRouter();const auth=useAuthStore();const loading=shallowRef(true);const detail=shallowRef<any>(null);const engineers=shallowRef<any[]>([])
const dispatchDialog=reactive<any>({visible:false,engineerId:null,teamId:null,reason:''});const recordDialog=reactive({visible:false});const cancelDialog=reactive<any>({visible:false,reason:'',equipmentTargetStatus:'RUNNING'})
const record=reactive<any>({inspectionProcess:'',rootCause:'',repairAction:'',repairResult:'',laborHours:0,downtimeMinutes:0,repairable:true})
const order=computed(()=>detail.value?.workOrder);const canProcess=computed(()=>auth.hasPermission('workorder:process')&&order.value?.assignedEngineerId===auth.currentUser?.userId)
async function load(showLoading=true){if(showLoading)loading.value=true;try{const fresh=(await api.detail(Number(route.params.id))).data;if(!showLoading){detail.value=null;await nextTick()}detail.value=fresh}catch(e:any){ElMessage.error(e.response?.data?.message||'工单详情加载失败')}finally{if(showLoading)loading.value=false}}
async function perform(action:()=>Promise<any>,message:string){try{await action();ElMessage.success(message);await load(false)}catch(e:any){ElMessage.error(e.response?.data?.message||'操作失败')}}
async function openDispatch(){try{engineers.value=(await api.engineers(order.value.id)).data;Object.assign(dispatchDialog,{visible:true,engineerId:null,teamId:null,reason:''})}catch(e:any){ElMessage.error(e.response?.data?.message||'工程师列表加载失败')}}
function engineerChanged(id:number){const item=engineers.value.find(i=>i.id===id);dispatchDialog.teamId=item?.teamId||null}
async function assign(){if(!dispatchDialog.engineerId)return ElMessage.warning('请选择工程师');await perform(()=>api.assign(order.value.id,{engineerId:dispatchDialog.engineerId,teamId:dispatchDialog.teamId,reason:dispatchDialog.reason}),'派单成功');dispatchDialog.visible=false}
async function reasonAction(kind:'suspend'|'resume'){try{const {value}=await ElMessageBox.prompt(kind==='suspend'?'请输入挂起原因':'请输入恢复处理说明',kind==='suspend'?'挂起工单':'恢复工单',{inputPattern:/\S+/,inputErrorMessage:'原因不能为空',type:'warning'});await perform(()=>api[kind](order.value.id,{reason:value}),kind==='suspend'?'工单已挂起':'工单已恢复处理')}catch(e:any){if(e!=='cancel')ElMessage.error(e.response?.data?.message||'操作失败')}}
function openRecord(){Object.assign(record,detail.value.repairRecord||{inspectionProcess:'',rootCause:'',repairAction:'',repairResult:'',laborHours:0,downtimeMinutes:0,repairable:true});recordDialog.visible=true}
async function saveRecord(){await perform(()=>api.saveRepairRecord(order.value.id,record),'维修记录已保存');recordDialog.visible=false}
async function submit(){try{await ElMessageBox.confirm('确认维修记录完整并提交验收？提交后将等待报修人或主管验收。','提交验收',{type:'warning'});await perform(()=>api.submitAcceptance(order.value.id),'已提交验收')}catch(e:any){if(e!=='cancel')ElMessage.error(e.response?.data?.message||'提交失败')}}
async function pass(){try{const {value}=await ElMessageBox.prompt('可填写验收意见','验收通过',{inputValue:'试运行正常',type:'success'});await perform(()=>api.pass(order.value.id,{remark:value}),'验收通过，设备已恢复运行')}catch(e:any){if(e!=='cancel')ElMessage.error(e.response?.data?.message||'验收失败')}}
async function reject(){try{const {value}=await ElMessageBox.prompt('请输入验收不通过原因','退回维修',{inputPattern:/\S+/,inputErrorMessage:'退回原因不能为空',type:'warning'});await perform(()=>api.reject(order.value.id,{reason:value}),'已退回工程师继续处理')}catch(e:any){if(e!=='cancel')ElMessage.error(e.response?.data?.message||'退回失败')}}
async function cancelOrder(){if(!cancelDialog.reason.trim())return ElMessage.warning('请输入取消原因');await perform(()=>api.cancel(order.value.id,{reason:cancelDialog.reason,equipmentTargetStatus:cancelDialog.equipmentTargetStatus}),'工单已取消');cancelDialog.visible=false}
const actionLabels:any={CREATE:'创建工单',ASSIGN:'人工派单',ACCEPT:'工程师接单',START:'开始维修',SUSPEND:'挂起',RESUME:'恢复',SUBMIT:'提交验收',ACCEPT_PASS:'验收通过',ACCEPT_RETURN:'验收退回',CANCEL:'取消'}
onMounted(load)
</script>

<template><section class="module-page" v-loading="loading"><header class="module-header"><div><p class="eyebrow">WORK ORDER DETAIL</p><h1>{{order?.workOrderNo||'工单详情'}}</h1><p v-if="order"><el-tag :type="workOrderStatusType(order.status)">{{workOrderStatusLabel(order.status)}}</el-tag> · {{order.equipmentName}}</p></div><div class="header-actions"><el-button @click="router.push('/work-orders')">返回列表</el-button><el-button v-if="order?.status==='PENDING_ASSIGN'" v-permission="'workorder:assign'" type="primary" @click="openDispatch">人工派单</el-button><el-button v-if="['PENDING_ASSIGN','ASSIGNED'].includes(order?.status)" v-permission="'workorder:cancel'" type="danger" plain @click="cancelDialog.visible=true">取消工单</el-button></div></header>
<template v-if="order"><el-card shadow="never"><template #header><div class="card-heading"><b>工单与报修信息</b><el-tag :type="priorityType(order.priority)">{{priorityLabel(order.priority)}}</el-tag></div></template><el-descriptions :column="3" border><el-descriptions-item label="设备">{{order.equipmentNo}} · {{order.equipmentName}}</el-descriptions-item><el-descriptions-item label="车间">{{order.workshopName}}</el-descriptions-item><el-descriptions-item label="报修人">{{order.reporterName}}</el-descriptions-item><el-descriptions-item label="工程师">{{order.assignedEngineerName||'待派单'}}</el-descriptions-item><el-descriptions-item label="负责班组">{{order.assignedTeamName||'-'}}</el-descriptions-item><el-descriptions-item label="退回次数">{{order.acceptanceReturnCount}}</el-descriptions-item><el-descriptions-item label="报修时间">{{detail.repairRequest?.reportedAt||'-'}}</el-descriptions-item><el-descriptions-item label="开始维修">{{order.startedAt||'-'}}</el-descriptions-item><el-descriptions-item label="完成时间">{{order.completedAt||'-'}}</el-descriptions-item><el-descriptions-item label="故障描述" :span="3">{{detail.repairRequest?.faultDescription||'-'}}</el-descriptions-item></el-descriptions></el-card>
<el-card v-show="canProcess&&['ASSIGNED','PROCESSING','SUSPENDED'].includes(order.status)" shadow="never" class="action-card"><template #header><b>工程师操作</b></template><div class="workflow-actions"><el-button v-show="order.status==='ASSIGNED'&&!order.acceptedAt" @click="perform(()=>api.acceptResponse(order.id),'接单成功')">确认接单</el-button><el-button v-show="order.status==='ASSIGNED'" type="primary" @click="perform(()=>api.start(order.id),'已开始维修，设备进入维修中')">开始维修</el-button><el-button v-show="order.status==='PROCESSING'" @click="openRecord">填写维修记录</el-button><el-button v-show="order.status==='PROCESSING'" type="warning" @click="reasonAction('suspend')">挂起</el-button><el-button v-show="order.status==='SUSPENDED'" type="primary" @click="reasonAction('resume')">恢复处理</el-button><el-button v-show="order.status==='PROCESSING'" type="success" @click="submit">提交验收</el-button></div></el-card>
<el-card v-show="order.status==='PENDING_ACCEPT'&&auth.hasPermission('workorder:accept')" shadow="never" class="action-card"><template #header><b>维修验收</b></template><p>请确认维修结果和试运行情况。验收通过后工单完成，设备恢复运行；不通过则退回处理中。</p><el-button type="success" @click="pass">验收通过</el-button><el-button type="warning" @click="reject">验收退回</el-button></el-card>
<div class="detail-grid"><el-card shadow="never"><template #header><b>维修记录</b></template><el-descriptions v-if="detail.repairRecord" :column="1" border><el-descriptions-item label="排查过程">{{detail.repairRecord.inspectionProcess||'-'}}</el-descriptions-item><el-descriptions-item label="根因分析">{{detail.repairRecord.rootCause||'-'}}</el-descriptions-item><el-descriptions-item label="处理措施">{{detail.repairRecord.repairAction||'-'}}</el-descriptions-item><el-descriptions-item label="维修结果">{{detail.repairRecord.repairResult||'-'}}</el-descriptions-item><el-descriptions-item label="工时/停机">{{detail.repairRecord.laborHours}} 小时 / {{detail.repairRecord.downtimeMinutes}} 分钟</el-descriptions-item></el-descriptions><el-empty v-else description="暂无维修记录"/></el-card><el-card shadow="never"><template #header><b>工单流转</b></template><el-timeline><el-timeline-item v-for="item in detail.flows" :key="item.id" :timestamp="item.createdAt" placement="top"><b>{{actionLabels[item.action]||item.action}}</b><p>{{workOrderStatusLabel(item.fromStatus)}} → {{workOrderStatusLabel(item.toStatus)}}</p><small>{{item.operatorName||`用户 ${item.operatorId}`}} · {{item.remark||'无备注'}}</small></el-timeline-item></el-timeline></el-card></div></template>
<el-dialog v-model="dispatchDialog.visible" title="人工派单" width="520px"><el-form label-width="90px"><el-form-item label="维修工程师" required><el-select v-model="dispatchDialog.engineerId" style="width:100%" @change="engineerChanged"><el-option v-for="item in engineers" :key="item.id" :label="`${item.realName} · ${item.teamName||'未分组'}`" :value="item.id"/></el-select></el-form-item><el-form-item label="负责班组"><el-input :model-value="engineers.find(i=>i.id===dispatchDialog.engineerId)?.teamName||'选择工程师后自动确定'" disabled/></el-form-item><el-form-item label="派单说明"><el-input v-model="dispatchDialog.reason" type="textarea" :rows="3"/></el-form-item></el-form><template #footer><el-button @click="dispatchDialog.visible=false">取消</el-button><el-button type="primary" @click="assign">确认派单</el-button></template></el-dialog>
<el-dialog v-model="recordDialog.visible" title="维修过程记录" width="680px"><el-form label-width="90px"><el-form-item label="排查过程" required><el-input v-model="record.inspectionProcess" type="textarea" :rows="2"/></el-form-item><el-form-item label="根因分析" required><el-input v-model="record.rootCause" type="textarea" :rows="2"/></el-form-item><el-form-item label="处理措施" required><el-input v-model="record.repairAction" type="textarea" :rows="2"/></el-form-item><el-form-item label="维修结果" required><el-input v-model="record.repairResult" type="textarea" :rows="2"/></el-form-item><el-form-item label="维修工时"><el-input-number v-model="record.laborHours" :min="0" :precision="2"/></el-form-item><el-form-item label="停机分钟"><el-input-number v-model="record.downtimeMinutes" :min="0"/></el-form-item><el-form-item label="是否修复"><el-switch v-model="record.repairable" active-text="已修复" inactive-text="无法修复"/></el-form-item></el-form><template #footer><el-button @click="recordDialog.visible=false">取消</el-button><el-button type="primary" @click="saveRecord">保存记录</el-button></template></el-dialog>
<el-dialog v-model="cancelDialog.visible" title="取消维修工单" width="520px"><el-alert title="取消不会机械恢复设备状态，请明确选择后续状态。" type="warning" :closable="false"/><el-form label-width="100px" class="dialog-form"><el-form-item label="取消原因" required><el-input v-model="cancelDialog.reason" type="textarea" :rows="3"/></el-form-item><el-form-item label="设备状态" required><el-radio-group v-model="cancelDialog.equipmentTargetStatus"><el-radio value="RUNNING">确认正常，恢复运行</el-radio><el-radio value="STOPPED">故障仍在，设备停用</el-radio></el-radio-group></el-form-item></el-form><template #footer><el-button @click="cancelDialog.visible=false">返回</el-button><el-button type="danger" @click="cancelOrder">确认取消</el-button></template></el-dialog></section></template>
