<script setup lang="ts">
import { computed, onMounted, reactive, shallowRef } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import * as api from '../../api/inventory'
import { useAuthStore } from '../../stores/auth'
import { stockStatusLabel, stockStatusType } from '../../utils/inventoryStatus'

const auth=useAuthStore(),loading=shallowRef(false),saving=shallowRef(false),rows=shallowRef<any[]>([]),warehouses=shallowRef<any[]>([]),spares=shallowRef<any[]>([]),warningRows=shallowRef<any[]>([]),total=shallowRef(0)
const query=reactive<any>({warehouseId:null,keyword:'',lowStockOnly:false,page:1,size:20})
const action=reactive<any>({visible:false,kind:'INBOUND',warehouseId:null,targetWarehouseId:null,sparePartId:null,qty:1,actualQty:0,unitPrice:null,remark:'',currentQty:0})
const title=computed(()=>({INBOUND:'备件入库',OUTBOUND:'普通出库',TRANSFER:'库存调拨',STOCKTAKE:'库存盘点',SCRAP:'备件报废'}[action.kind]))
async function load(){loading.value=true;try{const r=(await api.stocks(query)).data;rows.value=r.records;total.value=r.total;if(auth.hasPermission('inventory:warning:list'))warningRows.value=(await api.warnings()).data}catch(e:any){ElMessage.error(e.response?.data?.message||'库存加载失败')}finally{loading.value=false}}
async function loadOptions(){const [w,p]=await Promise.all([api.warehouses({status:'ENABLED',page:1,size:100}),api.spareParts({status:'ENABLED',page:1,size:100})]);warehouses.value=w.data.records;spares.value=p.data.records}
function open(kind:string,row:any=null){Object.assign(action,{visible:true,kind,warehouseId:row?.warehouseId||query.warehouseId||null,targetWarehouseId:null,sparePartId:row?.sparePartId||null,qty:1,actualQty:Number(row?.currentQty||0),unitPrice:null,remark:'',currentQty:Number(row?.currentQty||0)})}
async function submit(){if(!action.warehouseId||!action.sparePartId)return ElMessage.warning('请选择仓库和备件');if(action.kind==='TRANSFER'&&!action.targetWarehouseId)return ElMessage.warning('请选择目标仓库');if(action.kind!=='STOCKTAKE'&&Number(action.qty)<=0)return ElMessage.warning('数量必须大于0');if(!action.remark.trim()&&['STOCKTAKE','SCRAP'].includes(action.kind))return ElMessage.warning('请填写业务说明');
  const labels:any={INBOUND:'确认执行入库并生成库存流水？',OUTBOUND:'确认执行出库并扣减库存？',TRANSFER:'确认同时完成源仓扣减与目标仓增加？',STOCKTAKE:`系统数量 ${action.currentQty}，确认调整为 ${action.actualQty}？`,SCRAP:'报废将扣减库存且不可直接撤销，确认继续？'}
  try{await ElMessageBox.confirm(labels[action.kind],title.value,{type:action.kind==='SCRAP'?'warning':'info'});saving.value=true;const common={warehouseId:action.warehouseId,sparePartId:action.sparePartId,qty:action.qty,unitPrice:action.unitPrice,remark:action.remark};if(action.kind==='INBOUND')await api.inbound(common);if(action.kind==='OUTBOUND')await api.outbound(common);if(action.kind==='SCRAP')await api.scrap(common);if(action.kind==='TRANSFER')await api.transfer({sourceWarehouseId:action.warehouseId,targetWarehouseId:action.targetWarehouseId,sparePartId:action.sparePartId,qty:action.qty,remark:action.remark});if(action.kind==='STOCKTAKE')await api.stocktake({warehouseId:action.warehouseId,sparePartId:action.sparePartId,actualQty:action.actualQty,remark:action.remark});ElMessage.success(`${title.value}成功`);action.visible=false;await load()}catch(e:any){if(e!=='cancel')ElMessage.error(e.response?.data?.message||'库存操作失败')}finally{saving.value=false}}
onMounted(async()=>{try{await loadOptions()}catch(e:any){ElMessage.error(e.response?.data?.message||'基础数据加载失败')}await load()})
</script>

<template><section class="module-page">
  <header class="module-header"><div><p class="eyebrow">INVENTORY CONTROL</p><h1>库存管理</h1><p>当前数量按“仓库 + 备件”唯一维护，每次变化都生成不可编辑的库存流水。</p></div><div class="header-actions"><el-button v-permission="'inventory:transfer'" @click="open('TRANSFER')">调拨</el-button><el-button v-permission="'inventory:inbound'" type="primary" @click="open('INBOUND')">入库</el-button></div></header>
  <el-alert v-if="warningRows.length" :title="`当前有 ${warningRows.length} 项低库存预警`" description="补充库存达到建议安全库存后，系统会自动关闭对应预警。" type="warning" show-icon :closable="false"/>
  <el-card shadow="never" class="filter-card"><el-form inline><el-form-item label="仓库"><el-select v-model="query.warehouseId" clearable placeholder="全部仓库"><el-option v-for="w in warehouses" :key="w.id" :label="w.warehouseName" :value="w.id"/></el-select></el-form-item><el-form-item label="备件"><el-input v-model="query.keyword" clearable placeholder="编号或名称"/></el-form-item><el-form-item><el-checkbox v-model="query.lowStockOnly">仅看低库存</el-checkbox></el-form-item><el-form-item class="filter-actions"><el-button type="primary" @click="query.page=1;load()">查询</el-button><el-button @click="Object.assign(query,{warehouseId:null,keyword:'',lowStockOnly:false,page:1});load()">重置</el-button></el-form-item></el-form></el-card>
  <el-card shadow="never"><el-table v-loading="loading" :data="rows" stripe><el-table-column prop="warehouseName" label="仓库" min-width="130"/><el-table-column prop="spareNo" label="备件编号" min-width="130"/><el-table-column prop="spareName" label="备件名称" min-width="140"/><el-table-column prop="specification" label="规格" min-width="130" show-overflow-tooltip/><el-table-column label="当前库存" width="110" align="right"><template #default="{row}"><strong class="numeric">{{row.currentQty}} {{row.unit}}</strong></template></el-table-column><el-table-column label="建议安全库存" width="130" align="right"><template #default="{row}">{{row.suggestedSafetyStock}}</template></el-table-column><el-table-column label="补货点" width="100" align="right"><template #default="{row}">{{row.reorderPoint}}</template></el-table-column><el-table-column label="库存状态" width="130"><template #default="{row}"><el-tag :type="stockStatusType(row.stockStatus)">{{stockStatusLabel(row.stockStatus)}}</el-tag></template></el-table-column><el-table-column label="操作" width="235" fixed="right"><template #default="{row}"><el-button v-permission="'inventory:inbound'" link type="primary" @click="open('INBOUND',row)">入库</el-button><el-button v-permission="'inventory:outbound'" link @click="open('OUTBOUND',row)">出库</el-button><el-button v-permission="'inventory:stocktake'" link @click="open('STOCKTAKE',row)">盘点</el-button><el-button v-permission="'inventory:scrap'" link type="danger" @click="open('SCRAP',row)">报废</el-button></template></el-table-column><template #empty><el-empty description="暂无库存记录，可先执行入库" :image-size="72"/></template></el-table><div class="pagination-row"><el-pagination v-model:current-page="query.page" layout="total, prev, pager, next" :total="total" @current-change="load"/></div></el-card>
  <el-dialog v-model="action.visible" :title="title" width="560px"><el-form label-width="100px" class="dialog-form"><el-form-item label="源仓库" required><el-select v-model="action.warehouseId" style="width:100%" :disabled="action.kind==='STOCKTAKE'"><el-option v-for="w in warehouses" :key="w.id" :label="`${w.warehouseNo} · ${w.warehouseName}`" :value="w.id"/></el-select></el-form-item><el-form-item v-if="action.kind==='TRANSFER'" label="目标仓库" required><el-select v-model="action.targetWarehouseId" style="width:100%"><el-option v-for="w in warehouses" :key="w.id" :label="`${w.warehouseNo} · ${w.warehouseName}`" :value="w.id" :disabled="w.id===action.warehouseId"/></el-select></el-form-item><el-form-item label="备件" required><el-select v-model="action.sparePartId" filterable style="width:100%" :disabled="action.kind==='STOCKTAKE'"><el-option v-for="p in spares" :key="p.id" :label="`${p.spareNo} · ${p.spareName}`" :value="p.id"/></el-select></el-form-item><el-form-item v-if="action.kind==='STOCKTAKE'" label="系统数量"><strong>{{action.currentQty}}</strong></el-form-item><el-form-item v-if="action.kind==='STOCKTAKE'" label="实际数量" required><el-input-number v-model="action.actualQty" :min="0" :precision="2" style="width:100%"/></el-form-item><el-form-item v-else label="数量" required><el-input-number v-model="action.qty" :min="0.01" :precision="2" style="width:100%"/></el-form-item><el-form-item v-if="action.kind==='INBOUND'" label="当次单价"><el-input-number v-model="action.unitPrice" :min="0" :precision="2" placeholder="留空使用标准单价" style="width:100%"/></el-form-item><el-form-item label="业务说明" :required="['STOCKTAKE','SCRAP'].includes(action.kind)"><el-input v-model="action.remark" type="textarea" :rows="3" maxlength="500" show-word-limit/></el-form-item></el-form><template #footer><el-button @click="action.visible=false">取消</el-button><el-button type="primary" :loading="saving" @click="submit">确认提交</el-button></template></el-dialog>
</section></template>
