<script setup lang="ts">
import { onMounted, reactive, shallowRef } from 'vue'
import { ElMessage } from 'element-plus'
import * as api from '../../api/inventory'

const loading=shallowRef(false),saving=shallowRef(false),rows=shallowRef<any[]>([]),suppliers=shallowRef<any[]>([]),total=shallowRef(0)
const query=reactive({keyword:'',status:'',page:1,size:20})
const empty={id:null,spareNo:'',spareName:'',specification:'',brand:'',unit:'件',unitPrice:0,supplierId:null,compatibleModel:'',leadTimeDays:0,safetyDays:0,status:'ENABLED'}
const dialog=reactive<any>({visible:false,...empty})
async function load(){loading.value=true;try{const r=(await api.spareParts(query)).data;rows.value=r.records;total.value=r.total}catch(e:any){ElMessage.error(e.response?.data?.message||'备件列表加载失败')}finally{loading.value=false}}
async function open(row:any=null){if(!suppliers.value.length)try{suppliers.value=(await api.supplierOptions()).data}catch{};Object.assign(dialog,{visible:true,...empty,...(row||{})})}
async function save(){if(!dialog.spareNo.trim()||!dialog.spareName.trim()||!dialog.unit.trim())return ElMessage.warning('请填写备件编号、名称和单位');saving.value=true;try{const {visible,id,supplierName,createdAt,updatedAt,...payload}=dialog;if(id)await api.updateSparePart(id,payload);else await api.createSparePart(payload);ElMessage.success(id?'备件已更新':'备件已创建');dialog.visible=false;await load()}catch(e:any){ElMessage.error(e.response?.data?.message||'保存失败')}finally{saving.value=false}}
onMounted(load)
</script>

<template><section class="module-page">
  <header class="module-header"><div><p class="eyebrow">SPARE PART CATALOG</p><h1>备件管理</h1><p>统一维护备件规格、价格和安全库存参数；各仓库存量在库存页面查看。</p></div><el-button v-permission="'spare:manage'" type="primary" @click="open()">新增备件</el-button></header>
  <el-card shadow="never" class="filter-card"><el-form inline><el-form-item label="关键字"><el-input v-model="query.keyword" clearable placeholder="编号、名称或规格" @keyup.enter="query.page=1;load()"/></el-form-item><el-form-item label="状态"><el-select v-model="query.status" clearable placeholder="全部"><el-option label="启用" value="ENABLED"/><el-option label="停用" value="DISABLED"/></el-select></el-form-item><el-form-item class="filter-actions"><el-button type="primary" @click="query.page=1;load()">查询</el-button><el-button @click="Object.assign(query,{keyword:'',status:'',page:1});load()">重置</el-button></el-form-item></el-form></el-card>
  <el-card shadow="never"><el-table v-loading="loading" :data="rows" stripe><el-table-column prop="spareNo" label="备件编号" min-width="130"/><el-table-column prop="spareName" label="备件名称" min-width="140"/><el-table-column prop="specification" label="规格" min-width="140" show-overflow-tooltip/><el-table-column prop="brand" label="品牌" width="110"><template #default="{row}">{{row.brand||'-'}}</template></el-table-column><el-table-column prop="unit" label="单位" width="70"/><el-table-column label="单价" width="100" align="right"><template #default="{row}">¥ {{Number(row.unitPrice).toFixed(2)}}</template></el-table-column><el-table-column prop="supplierName" label="供应商" min-width="150"><template #default="{row}">{{row.supplierName||'-'}}</template></el-table-column><el-table-column label="安全参数" width="130"><template #default="{row}">{{row.leadTimeDays}} / {{row.safetyDays}} 天</template></el-table-column><el-table-column label="状态" width="80"><template #default="{row}"><el-tag :type="row.status==='ENABLED'?'success':'info'">{{row.status==='ENABLED'?'启用':'停用'}}</el-tag></template></el-table-column><el-table-column label="操作" width="90" fixed="right"><template #default="{row}"><el-button v-permission="'spare:manage'" link type="primary" @click="open(row)">编辑</el-button></template></el-table-column><template #empty><el-empty description="暂无备件" :image-size="72"/></template></el-table><div class="pagination-row"><el-pagination v-model:current-page="query.page" layout="total, prev, pager, next" :total="total" @current-change="load"/></div></el-card>
  <el-dialog v-model="dialog.visible" :title="dialog.id?'编辑备件':'新增备件'" width="700px"><el-form label-width="90px" class="inventory-form"><el-form-item label="备件编号" required><el-input v-model="dialog.spareNo"/></el-form-item><el-form-item label="备件名称" required><el-input v-model="dialog.spareName"/></el-form-item><el-form-item label="规格"><el-input v-model="dialog.specification"/></el-form-item><el-form-item label="品牌"><el-input v-model="dialog.brand"/></el-form-item><el-form-item label="计量单位" required><el-input v-model="dialog.unit"/></el-form-item><el-form-item label="标准单价" required><el-input-number v-model="dialog.unitPrice" :min="0" :precision="2" style="width:100%"/></el-form-item><el-form-item label="供应商"><el-select v-model="dialog.supplierId" clearable style="width:100%"><el-option v-for="s in suppliers" :key="s.id" :label="s.supplierName" :value="s.id"/></el-select></el-form-item><el-form-item label="适配型号"><el-input v-model="dialog.compatibleModel"/></el-form-item><el-form-item label="采购提前期"><el-input-number v-model="dialog.leadTimeDays" :min="0" style="width:100%"/></el-form-item><el-form-item label="安全天数"><el-input-number v-model="dialog.safetyDays" :min="0" style="width:100%"/></el-form-item><el-form-item label="状态"><el-radio-group v-model="dialog.status"><el-radio value="ENABLED">启用</el-radio><el-radio value="DISABLED">停用</el-radio></el-radio-group></el-form-item></el-form><template #footer><el-button @click="dialog.visible=false">取消</el-button><el-button type="primary" :loading="saving" @click="save">保存</el-button></template></el-dialog>
</section></template>
