<script setup lang="ts">
import { onMounted, reactive, shallowRef } from 'vue'
import { ElMessage } from 'element-plus'
import * as api from '../../api/inventory'
import { transactionLabel, transactionTagType, transactionTypes } from '../../utils/inventoryStatus'

const loading=shallowRef(false),rows=shallowRef<any[]>([]),warehouses=shallowRef<any[]>([]),total=shallowRef(0)
const query=reactive<any>({warehouseId:null,transactionType:'',workOrderId:null,startDate:null,endDate:null,page:1,size:20})
async function load(){loading.value=true;try{const r=(await api.transactions(query)).data;rows.value=r.records;total.value=r.total}catch(e:any){ElMessage.error(e.response?.data?.message||'库存流水加载失败')}finally{loading.value=false}}
onMounted(async()=>{try{warehouses.value=(await api.warehouses({status:'ENABLED',page:1,size:100})).data.records}catch{}await load()})
</script>

<template><section class="module-page">
  <header class="module-header"><div><p class="eyebrow">STOCK MOVEMENT LEDGER</p><h1>库存流水</h1><p>按时间追溯每次库存变化、业务来源、工单和操作人；历史流水不提供修改或删除。</p></div></header>
  <el-card shadow="never" class="filter-card"><el-form inline><el-form-item label="仓库"><el-select v-model="query.warehouseId" clearable placeholder="全部"><el-option v-for="w in warehouses" :key="w.id" :label="w.warehouseName" :value="w.id"/></el-select></el-form-item><el-form-item label="流水类型"><el-select v-model="query.transactionType" clearable placeholder="全部"><el-option v-for="(item,key) in transactionTypes" :key="key" :label="item.label" :value="key"/></el-select></el-form-item><el-form-item label="工单 ID"><el-input-number v-model="query.workOrderId" :min="1" :controls="false"/></el-form-item><el-form-item class="filter-actions"><el-button type="primary" @click="query.page=1;load()">查询</el-button><el-button @click="Object.assign(query,{warehouseId:null,transactionType:'',workOrderId:null,startDate:null,endDate:null,page:1});load()">重置</el-button></el-form-item></el-form></el-card>
  <el-card shadow="never"><el-table v-loading="loading" :data="rows" stripe><el-table-column prop="createdAt" label="时间" width="168"/><el-table-column prop="transactionNo" label="流水号" min-width="210" show-overflow-tooltip/><el-table-column label="类型" width="110"><template #default="{row}"><el-tag :type="transactionTagType(row.transactionType)" effect="plain">{{transactionLabel(row.transactionType)}}</el-tag></template></el-table-column><el-table-column prop="warehouseName" label="仓库" min-width="120"/><el-table-column label="备件" min-width="180"><template #default="{row}"><strong>{{row.spareName}}</strong><small class="table-subtitle">{{row.spareNo}}</small></template></el-table-column><el-table-column label="数量变化" width="105" align="right"><template #default="{row}"><strong :class="['qty-change',Number(row.qtyChange)>0?'positive':'negative']">{{Number(row.qtyChange)>0?'+':''}}{{row.qtyChange}}</strong></template></el-table-column><el-table-column label="变更后" width="90" align="right"><template #default="{row}">{{row.qtyAfter}}</template></el-table-column><el-table-column label="关联业务" min-width="150"><template #default="{row}">{{row.workOrderNo||row.equipmentNo||'-'}}</template></el-table-column><el-table-column prop="operatorName" label="操作人" width="110"/><el-table-column prop="remark" label="说明" min-width="160" show-overflow-tooltip/><template #empty><el-empty description="暂无库存流水" :image-size="72"/></template></el-table><div class="pagination-row"><el-pagination v-model:current-page="query.page" layout="total, prev, pager, next" :total="total" @current-change="load"/></div></el-card>
</section></template>
