<script setup lang="ts">
import { onMounted, reactive, shallowRef } from 'vue'
import { ElMessage } from 'element-plus'
import * as api from '../../api/inventory'
import { useAuthStore } from '../../stores/auth'

const auth=useAuthStore(),loading=shallowRef(false),saving=shallowRef(false),rows=shallowRef<any[]>([]),users=shallowRef<any[]>([])
const total=shallowRef(0),query=reactive({keyword:'',status:'',page:1,size:20})
const dialog=reactive<any>({visible:false,id:null,warehouseNo:'',warehouseName:'',location:'',managerId:null,status:'ENABLED',authorizedUserIds:[]})
async function load(){loading.value=true;try{const r=(await api.warehouses(query)).data;rows.value=r.records;total.value=r.total}catch(e:any){ElMessage.error(e.response?.data?.message||'仓库列表加载失败')}finally{loading.value=false}}
async function loadUsers(){if(auth.hasPermission('warehouse:authorize')&&!users.value.length)users.value=(await api.authorizedUserOptions()).data}
async function open(row:any=null){await loadUsers();Object.assign(dialog,{visible:true,id:row?.id||null,warehouseNo:row?.warehouseNo||'',warehouseName:row?.warehouseName||'',location:row?.location||'',managerId:row?.managerId||null,status:row?.status||'ENABLED',authorizedUserIds:row?.authorizedUserIds||[]})}
async function save(){if(!dialog.warehouseNo.trim()||!dialog.warehouseName.trim())return ElMessage.warning('请填写仓库编号和名称');saving.value=true;try{const payload={warehouseNo:dialog.warehouseNo,warehouseName:dialog.warehouseName,location:dialog.location,managerId:dialog.managerId,status:dialog.status};let id=dialog.id;if(id)await api.updateWarehouse(id,payload);else id=(await api.createWarehouse(payload)).data;if(auth.hasPermission('warehouse:authorize'))await api.authorizeWarehouse(id,dialog.authorizedUserIds);ElMessage.success(dialog.id?'仓库已更新':'仓库已创建');dialog.visible=false;await load()}catch(e:any){ElMessage.error(e.response?.data?.message||'保存失败')}finally{saving.value=false}}
onMounted(load)
</script>

<template><section class="module-page">
  <header class="module-header"><div><p class="eyebrow">WAREHOUSE DIRECTORY</p><h1>仓库管理</h1><p>维护仓库基础信息与人员授权，历史库存业务不随仓库停用而删除。</p></div><el-button v-permission="'warehouse:manage'" type="primary" @click="open()">新增仓库</el-button></header>
  <el-card shadow="never" class="filter-card"><el-form inline><el-form-item label="关键字"><el-input v-model="query.keyword" clearable placeholder="编号、名称或位置" @keyup.enter="query.page=1;load()"/></el-form-item><el-form-item label="状态"><el-select v-model="query.status" clearable placeholder="全部"><el-option label="启用" value="ENABLED"/><el-option label="停用" value="DISABLED"/></el-select></el-form-item><el-form-item class="filter-actions"><el-button type="primary" @click="query.page=1;load()">查询</el-button><el-button @click="Object.assign(query,{keyword:'',status:'',page:1});load()">重置</el-button></el-form-item></el-form></el-card>
  <el-card shadow="never"><el-table v-loading="loading" :data="rows" stripe><el-table-column prop="warehouseNo" label="仓库编号" min-width="130"/><el-table-column prop="warehouseName" label="仓库名称" min-width="150"/><el-table-column prop="location" label="位置" min-width="180" show-overflow-tooltip/><el-table-column prop="managerName" label="负责人" width="120"><template #default="{row}">{{row.managerName||'-'}}</template></el-table-column><el-table-column label="授权人数" width="100" align="center"><template #default="{row}">{{row.authorizedUserIds?.length||0}}</template></el-table-column><el-table-column label="状态" width="90"><template #default="{row}"><el-tag :type="row.status==='ENABLED'?'success':'info'">{{row.status==='ENABLED'?'启用':'停用'}}</el-tag></template></el-table-column><el-table-column label="操作" width="100" fixed="right"><template #default="{row}"><el-button v-permission="'warehouse:manage'" link type="primary" @click="open(row)">编辑</el-button></template></el-table-column><template #empty><el-empty description="暂无仓库" :image-size="72"/></template></el-table><div class="pagination-row"><el-pagination v-model:current-page="query.page" v-model:page-size="query.size" layout="total, prev, pager, next" :total="total" @current-change="load"/></div></el-card>
  <el-dialog v-model="dialog.visible" :title="dialog.id?'编辑仓库':'新增仓库'" width="580px"><el-form label-width="90px" class="dialog-form"><el-form-item label="仓库编号" required><el-input v-model="dialog.warehouseNo" maxlength="50"/></el-form-item><el-form-item label="仓库名称" required><el-input v-model="dialog.warehouseName" maxlength="100"/></el-form-item><el-form-item label="位置"><el-input v-model="dialog.location" maxlength="255"/></el-form-item><el-form-item v-if="auth.hasPermission('warehouse:authorize')" label="负责人"><el-select v-model="dialog.managerId" clearable filterable style="width:100%"><el-option v-for="u in users" :key="u.id" :label="`${u.realName} · ${u.jobTitle||u.username}`" :value="u.id"/></el-select></el-form-item><el-form-item label="状态"><el-radio-group v-model="dialog.status"><el-radio value="ENABLED">启用</el-radio><el-radio value="DISABLED">停用</el-radio></el-radio-group></el-form-item><el-form-item v-if="auth.hasPermission('warehouse:authorize')" label="授权用户"><el-select v-model="dialog.authorizedUserIds" multiple filterable style="width:100%" placeholder="仓管员或需领料的工程师"><el-option v-for="u in users" :key="u.id" :label="`${u.realName} · ${u.jobTitle||u.username}`" :value="u.id"/></el-select></el-form-item></el-form><template #footer><el-button @click="dialog.visible=false">取消</el-button><el-button type="primary" :loading="saving" @click="save">保存</el-button></template></el-dialog>
</section></template>
