import http from './http'

export const warehouses = (params) => http.get('/warehouses', { params })
export const warehouseDetail = (id) => http.get(`/warehouses/${id}`)
export const createWarehouse = (data) => http.post('/warehouses', data)
export const updateWarehouse = (id, data) => http.put(`/warehouses/${id}`, data)
export const authorizeWarehouse = (id, userIds) => http.put(`/warehouses/${id}/authorized-users`, { userIds })
export const authorizedUserOptions = () => http.get('/warehouses/authorized-user-options')
export const spareParts = (params) => http.get('/spare-parts', { params })
export const createSparePart = (data) => http.post('/spare-parts', data)
export const updateSparePart = (id, data) => http.put(`/spare-parts/${id}`, data)
export const supplierOptions = () => http.get('/spare-parts/suppliers/options')
export const stocks = (params) => http.get('/inventory/stocks', { params })
export const transactions = (params) => http.get('/inventory/transactions', { params })
export const inbound = (data) => http.post('/inventory/inbound', data)
export const outbound = (data) => http.post('/inventory/outbound', data)
export const scrap = (data) => http.post('/inventory/scrap', data)
export const transfer = (data) => http.post('/inventory/transfer', data)
export const stocktake = (data) => http.post('/inventory/stocktake', data)
export const warnings = () => http.get('/inventory/warnings')
