import http from './http'
export const tree = (params) => http.get('/organizations/tree', { params })
export const workshops = (params) => http.get('/organizations/workshops', { params })
export const createWorkshop = (data) => http.post('/organizations/workshops', data)
export const updateWorkshop = (id, data) => http.put(`/organizations/workshops/${id}`, data)
export const deleteWorkshop = (id) => http.delete(`/organizations/workshops/${id}`)
export const lines = (params) => http.get('/organizations/lines', { params })
export const createLine = (data) => http.post('/organizations/lines', data)
export const updateLine = (id, data) => http.put(`/organizations/lines/${id}`, data)
export const deleteLine = (id) => http.delete(`/organizations/lines/${id}`)
export const stations = (params) => http.get('/organizations/stations', { params })
export const createStation = (data) => http.post('/organizations/stations', data)
export const updateStation = (id, data) => http.put(`/organizations/stations/${id}`, data)
export const deleteStation = (id) => http.delete(`/organizations/stations/${id}`)
export const teams = (params) => http.get('/organizations/teams', { params })
