import http from './http'
export const page = (params) => http.get('/work-orders', { params })
export const detail = (id) => http.get(`/work-orders/${id}`)
export const exportPdf = (id) => http.get(`/work-orders/${id}/pdf`, { responseType: 'blob' })
export const attachments = (id) => http.get(`/work-orders/${id}/attachments`)
export const uploadAttachment = (id, type, file) => { const data = new FormData(); data.append('file', file); return http.post(`/work-orders/${id}/attachments`, data, { params: { type } }) }
export const downloadAttachment = (id, attachmentId) => http.get(`/work-orders/${id}/attachments/${attachmentId}`, { responseType: 'blob' })
export const engineers = (id) => http.get(`/work-orders/${id}/engineers`)
export const dispatchCandidates = (id) => http.get(`/work-orders/${id}/dispatch-candidates`)
export const similar = (id) => http.get(`/work-orders/${id}/similar`)
export const similarByDescription = (description) => http.get('/work-orders/similar', { params: { description } })
export const assign = (id, data) => http.post(`/work-orders/${id}/assign`, data)
export const acceptResponse = (id) => http.post(`/work-orders/${id}/accept`)
export const start = (id) => http.post(`/work-orders/${id}/start`)
export const suspend = (id, data) => http.post(`/work-orders/${id}/suspend`, data)
export const resume = (id, data) => http.post(`/work-orders/${id}/resume`, data)
export const saveRepairRecord = (id, data) => http.put(`/work-orders/${id}/repair-record`, data)
export const submitAcceptance = (id) => http.post(`/work-orders/${id}/submit-acceptance`)
export const pass = (id, data) => http.post(`/work-orders/${id}/acceptance/pass`, data)
export const reject = (id, data) => http.post(`/work-orders/${id}/acceptance/reject`, data)
export const cancel = (id, data) => http.post(`/work-orders/${id}/cancel`, data)
export const issueSpare = (id, data) => http.post(`/work-orders/${id}/spares`, data)
export const returnSpare = (id, issueId, data) => http.post(`/work-orders/${id}/spares/${issueId}/return`, data)
