package com.cq.maintenance.inventory;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.*;
import com.cq.maintenance.common.exception.*;
import com.cq.maintenance.inventory.dto.*;
import com.cq.maintenance.inventory.entity.*;
import com.cq.maintenance.inventory.mapper.InventoryMapper;
import com.cq.maintenance.inventory.mapper.InventoryMapper.StockRow;
import com.cq.maintenance.inventory.service.InventoryService;
import com.cq.maintenance.security.LoginUser;
import com.cq.maintenance.workorder.entity.*;
import com.cq.maintenance.workorder.mapper.WorkOrderMapper;
import com.cq.maintenance.workorder.service.*;
import java.math.BigDecimal;
import java.util.List;
import org.junit.jupiter.api.*;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.core.context.SecurityContextHolder;

class InventoryServiceTest {
    InventoryMapper mapper;WorkOrderMapper workOrders;WorkOrderScopeService scopes;BusinessNumberService numbers;InventoryService service;
    Warehouse wh1,wh2;SparePart spare;
    @BeforeEach void setUp(){mapper=mock(InventoryMapper.class);workOrders=mock(WorkOrderMapper.class);scopes=mock(WorkOrderScopeService.class);numbers=mock(BusinessNumberService.class);service=new InventoryService(mapper,workOrders,scopes,numbers);login("ADMIN",List.of());wh1=warehouse(1L);wh2=warehouse(2L);spare=spare(3L);when(mapper.findWarehouse(1L)).thenReturn(wh1);when(mapper.findWarehouse(2L)).thenReturn(wh2);when(mapper.findSparePart(3L)).thenReturn(spare);when(mapper.sumNetOutbound(anyLong(),anyLong(),anyInt())).thenReturn(BigDecimal.ZERO);when(mapper.findOpenWarning(anyLong(),anyLong())).thenReturn(null);when(numbers.next("TX")).thenReturn("TX1","TX2","TX3");doAnswer(i->{((InventoryTransaction)i.getArgument(0)).setId(90L);return 1;}).when(mapper).insertTransaction(any());doAnswer(i->{((WorkOrderSpare)i.getArgument(0)).setId(91L);return 1;}).when(mapper).insertWorkOrderSpare(any());doAnswer(i->{((InventoryMapper.WarningInsert)i.getArgument(0)).setId(92L);return 1;}).when(mapper).insertWarning(any());}
    @AfterEach void clear(){SecurityContextHolder.clearContext();}
    void login(String role,List<Long> warehouses){LoginUser u=new LoginUser(7L,"user","用户","ENABLED",List.of(role),List.of(),List.of(4L),5L,warehouses);SecurityContextHolder.getContext().setAuthentication(UsernamePasswordAuthenticationToken.authenticated(u,null,List.of()));}
    Warehouse warehouse(Long id){Warehouse w=new Warehouse();w.setId(id);w.setWarehouseNo("WH"+id);w.setWarehouseName("仓库"+id);w.setStatus("ENABLED");return w;}
    SparePart spare(Long id){SparePart p=new SparePart();p.setId(id);p.setSpareNo("SP"+id);p.setSpareName("轴承");p.setUnit("件");p.setUnitPrice(new BigDecimal("10.00"));p.setLeadTimeDays(5);p.setSafetyDays(3);p.setStatus("ENABLED");return p;}
    void stock(Long warehouse,BigDecimal qty){when(mapper.lockStock(warehouse,3L)).thenReturn(new StockRow(warehouse+10,warehouse,3L,qty));}
    InventoryOperationRequest operation(Long warehouse,String qty){return new InventoryOperationRequest(warehouse,3L,new BigDecimal(qty),null,"测试");}
    WorkOrder processing(){WorkOrder w=new WorkOrder();w.setId(8L);w.setEquipmentId(9L);w.setAssignedEngineerId(7L);w.setWorkOrderType(WorkOrderType.REPAIR);w.setStatus(WorkOrderStatus.PROCESSING);when(workOrders.lockWorkOrder(8L)).thenReturn(w);return w;}

    @Test void createsWarehouseAndAutoAuthorizesWarehouseAdmin(){login("WAREHOUSE_ADMIN",List.of());doAnswer(i->{((Warehouse)i.getArgument(0)).setId(12L);return 1;}).when(mapper).insertWarehouse(any());assertEquals(12L,service.createWarehouse(new WarehouseRequest("WH-12","新仓",null,null,"ENABLED")));verify(mapper).insertWarehouseUsers(12L,List.of(7L));}
    @Test void rejectsDuplicateWarehouseCode(){when(mapper.countWarehouseCode("WH1",null)).thenReturn(1L);BusinessException e=assertThrows(BusinessException.class,()->service.createWarehouse(new WarehouseRequest("WH1","仓库",null,null,"ENABLED")));assertEquals(ErrorCode.BUSINESS_CONFLICT,e.getErrorCode());}
    @Test void warehouseAdminCannotEditOtherWarehouse(){login("WAREHOUSE_ADMIN",List.of(2L));assertThrows(BusinessException.class,()->service.updateWarehouse(1L,new WarehouseRequest("WH1","仓库",null,null,"ENABLED")));verify(mapper,never()).updateWarehouse(any());}
    @Test void createsSparePartWithBigDecimalPrice(){doAnswer(i->{((SparePart)i.getArgument(0)).setId(15L);return 1;}).when(mapper).insertSparePart(any());Long id=service.createSparePart(new SparePartRequest("SP15","密封圈",null,null,"件",new BigDecimal("12.35"),null,null,2,4,"ENABLED"));assertEquals(15L,id);verify(mapper).insertSparePart(argThat(p->new BigDecimal("12.35").equals(p.getUnitPrice())));}
    @Test void rejectsDuplicateSpareCode(){when(mapper.countSparePartCode("SP3",null)).thenReturn(1L);assertThrows(BusinessException.class,()->service.createSparePart(new SparePartRequest("SP3","轴承",null,null,"件",BigDecimal.ONE,null,null,1,1,"ENABLED")));}
    @Test void engineerCannotPerformOrdinaryInventoryMutation(){login("ENGINEER",List.of(1L));assertThrows(BusinessException.class,()->service.inbound(operation(1L,"2")));verify(mapper,never()).updateStock(anyLong(),any());}
    @Test void inboundIncreasesStockAndWritesInboundLedger(){stock(1L,new BigDecimal("5.00"));service.inbound(operation(1L,"2.00"));verify(mapper).updateStock(11L,new BigDecimal("7.00"));verify(mapper).insertTransaction(argThat(t->"INBOUND".equals(t.getTransactionType())&&new BigDecimal("5.00").equals(t.getQtyBefore())&&new BigDecimal("7.00").equals(t.getQtyAfter())));}
    @Test void outboundDecreasesStockAndWritesLedger(){stock(1L,new BigDecimal("5.00"));service.outbound(operation(1L,"2.00"));verify(mapper).updateStock(11L,new BigDecimal("3.00"));verify(mapper).insertTransaction(argThat(t->"OUTBOUND".equals(t.getTransactionType())&&t.getQtyChange().signum()<0));}
    @Test void insufficientOutboundLeavesStockUnchanged(){stock(1L,new BigDecimal("1.00"));BusinessException e=assertThrows(BusinessException.class,()->service.outbound(operation(1L,"2.00")));assertEquals(ErrorCode.INSUFFICIENT_STOCK,e.getErrorCode());verify(mapper,never()).updateStock(anyLong(),any());verify(mapper,never()).insertTransaction(any());}
    @Test void transferMovesBothStocksAndCreatesPairedTransactions(){stock(1L,new BigDecimal("9.00"));stock(2L,new BigDecimal("1.00"));service.transfer(new TransferRequest(1L,2L,3L,new BigDecimal("4.00"),"补货"));verify(mapper).updateStock(11L,new BigDecimal("5.00"));verify(mapper).updateStock(12L,new BigDecimal("5.00"));verify(mapper,times(2)).insertTransaction(any());verify(mapper).updateTransactionRelated(90L,90L);}
    @Test void rejectsTransferToSameWarehouse(){assertThrows(BusinessException.class,()->service.transfer(new TransferRequest(1L,1L,3L,BigDecimal.ONE,"错误调拨")));}
    @Test void stocktakeGainUsesSingleAdjustmentLedger(){stock(1L,new BigDecimal("5.00"));service.stocktake(new StocktakeRequest(1L,3L,new BigDecimal("8.00"),"盘盈"));verify(mapper).updateStock(11L,new BigDecimal("8.00"));verify(mapper).insertTransaction(argThat(t->"STOCKTAKE".equals(t.getTransactionType())&&t.getQtyChange().compareTo(new BigDecimal("3.00"))==0));}
    @Test void stocktakeLossUsesNegativeAdjustmentLedger(){stock(1L,new BigDecimal("5.00"));service.stocktake(new StocktakeRequest(1L,3L,new BigDecimal("2.00"),"盘亏"));verify(mapper).insertTransaction(argThat(t->"STOCKTAKE".equals(t.getTransactionType())&&t.getQtyChange().signum()<0));}
    @Test void rejectsNoDifferenceStocktake(){stock(1L,new BigDecimal("5.00"));BusinessException e=assertThrows(BusinessException.class,()->service.stocktake(new StocktakeRequest(1L,3L,new BigDecimal("5.00"),"复核")));assertEquals(ErrorCode.DUPLICATE_OPERATION,e.getErrorCode());}
    @Test void workOrderIssueDeductsStockAndCreatesFormalRelation(){login("ENGINEER",List.of(1L));processing();stock(1L,new BigDecimal("6.00"));assertNotNull(service.issueForWorkOrder(8L,new WorkOrderSpareRequest(1L,3L,new BigDecimal("2.00"),"更换轴承")));verify(mapper).updateStock(11L,new BigDecimal("4.00"));verify(mapper).insertWorkOrderSpare(argThat(i->i.getWorkOrderId().equals(8L)&&i.getTransactionId().equals(90L)&&"ISSUED".equals(i.getStatus())));}
    @Test void completedWorkOrderCannotIssue(){login("ENGINEER",List.of(1L));WorkOrder order=processing();order.setStatus(WorkOrderStatus.COMPLETED);assertThrows(BusinessException.class,()->service.issueForWorkOrder(8L,new WorkOrderSpareRequest(1L,3L,BigDecimal.ONE,"")));}
    @Test void nonAssignedEngineerCannotIssue(){login("ENGINEER",List.of(1L));processing();doThrow(new BusinessException(ErrorCode.DATA_FORBIDDEN)).when(scopes).assertAssignedEngineer(any());assertThrows(BusinessException.class,()->service.issueForWorkOrder(8L,new WorkOrderSpareRequest(1L,3L,BigDecimal.ONE,"")));verify(mapper,never()).updateStock(anyLong(),any());}
    @Test void returnRestoresStockAndMarksPartial(){login("ENGINEER",List.of(1L));processing();WorkOrderSpare issue=new WorkOrderSpare();issue.setId(20L);issue.setWorkOrderId(8L);issue.setWarehouseId(1L);issue.setSparePartId(3L);issue.setQty(new BigDecimal("5.00"));issue.setUnitPriceSnapshot(BigDecimal.TEN);issue.setTransactionId(21L);when(mapper.lockWorkOrderSpare(20L)).thenReturn(issue);when(mapper.sumReturned(21L)).thenReturn(new BigDecimal("1.00"));stock(1L,new BigDecimal("3.00"));service.returnForWorkOrder(8L,20L,new ReturnSpareRequest(new BigDecimal("2.00"),"未使用"));verify(mapper).updateStock(11L,new BigDecimal("5.00"));verify(mapper).updateIssueStatus(20L,"PARTIAL_RETURN");verify(mapper).insertTransaction(argThat(t->"RETURN".equals(t.getTransactionType())&&Long.valueOf(21L).equals(t.getRelatedTransactionId())));}
    @Test void rejectsReturnBeyondRemainingQuantity(){login("ENGINEER",List.of(1L));processing();WorkOrderSpare issue=new WorkOrderSpare();issue.setId(20L);issue.setWorkOrderId(8L);issue.setQty(new BigDecimal("5"));issue.setTransactionId(21L);when(mapper.lockWorkOrderSpare(20L)).thenReturn(issue);when(mapper.sumReturned(21L)).thenReturn(new BigDecimal("3"));assertThrows(BusinessException.class,()->service.returnForWorkOrder(8L,20L,new ReturnSpareRequest(new BigDecimal("3"),"超额")));verify(mapper,never()).updateStock(anyLong(),any());}
    @Test void completedWorkOrderCannotReturn(){login("ENGINEER",List.of(1L));WorkOrder order=processing();order.setStatus(WorkOrderStatus.COMPLETED);assertThrows(BusinessException.class,()->service.returnForWorkOrder(8L,20L,new ReturnSpareRequest(BigDecimal.ONE,"完成后退库")));}
    @Test void lowStockCreatesWarningAndNotification(){stock(1L,new BigDecimal("4.00"));when(mapper.sumNetOutbound(1L,3L,30)).thenReturn(new BigDecimal("60.00"));service.outbound(operation(1L,"2.00"));verify(mapper).insertWarning(any());verify(mapper).insertWarningMessages(eq(1L),eq(92L),contains("轴承"));}
    @Test void replenishmentClosesOpenWarning(){stock(1L,new BigDecimal("2.00"));when(mapper.sumNetOutbound(1L,3L,30)).thenReturn(new BigDecimal("30.00"));when(mapper.findOpenWarning(1L,3L)).thenReturn(55L);service.inbound(operation(1L,"2.00"));verify(mapper).closeWarning(55L,new BigDecimal("4.00"));}
    @Test void disabledWarehouseRejectsInbound(){wh1.setStatus("DISABLED");assertThrows(BusinessException.class,()->service.inbound(operation(1L,"1")));}
    @Test void disabledSpareRejectsOutbound(){spare.setStatus("DISABLED");assertThrows(BusinessException.class,()->service.outbound(operation(1L,"1")));}
    @Test void scrapDeductsAndUsesScrapType(){stock(1L,new BigDecimal("3"));service.scrap(operation(1L,"1"));verify(mapper).insertTransaction(argThat(t->"SCRAP".equals(t.getTransactionType())));}
    @Test void fullReturnMarksReturned(){login("ENGINEER",List.of(1L));processing();WorkOrderSpare issue=new WorkOrderSpare();issue.setId(20L);issue.setWorkOrderId(8L);issue.setWarehouseId(1L);issue.setSparePartId(3L);issue.setQty(new BigDecimal("2"));issue.setUnitPriceSnapshot(BigDecimal.TEN);issue.setTransactionId(21L);when(mapper.lockWorkOrderSpare(20L)).thenReturn(issue);when(mapper.sumReturned(21L)).thenReturn(BigDecimal.ONE);stock(1L,BigDecimal.ZERO);service.returnForWorkOrder(8L,20L,new ReturnSpareRequest(BigDecimal.ONE,"全部退回"));verify(mapper).updateIssueStatus(20L,"RETURNED");}
    @Test void unauthorizedWarehouseCannotBeQueriedDirectly(){login("WAREHOUSE_ADMIN",List.of(2L));StockQuery q=new StockQuery();q.setWarehouseId(1L);assertThrows(BusinessException.class,()->service.stocks(q));}
    @Test void safetyStockUsesFrozenFormula(){when(mapper.sumNetOutbound(1L,3L,30)).thenReturn(new BigDecimal("60"));var result=service.safetyStock(1L,3L);assertEquals(new BigDecimal("2.00"),result.dailyConsumption());assertEquals(new BigDecimal("6.00"),result.suggestedSafetyStock());assertEquals(new BigDecimal("16.00"),result.reorderPoint());}
    @Test void invalidManagerIsRejected(){when(mapper.countEnabledUser(99L)).thenReturn(0L);assertThrows(BusinessException.class,()->service.createWarehouse(new WarehouseRequest("WH9","仓库",null,99L,"ENABLED")));}
    @Test void invalidSupplierIsRejected(){when(mapper.countEnabledSupplier(99L)).thenReturn(0L);assertThrows(BusinessException.class,()->service.createSparePart(new SparePartRequest("SP9","备件",null,null,"件",BigDecimal.ONE,99L,null,1,1,"ENABLED")));}
    @Test void invalidWarehouseAuthorizationUserIsRejected(){when(mapper.countWarehouseAssignableUser(99L)).thenReturn(0L);assertThrows(BusinessException.class,()->service.authorizeWarehouse(1L,new WarehouseAuthorizationRequest(List.of(99L))));verify(mapper,never()).clearWarehouseUsers(anyLong());}
}
