package com.cq.maintenance.sla.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.cq.maintenance.repair.entity.RepairPriority;
import com.cq.maintenance.sla.dto.SlaEventQuery;
import com.cq.maintenance.sla.entity.*;
import com.cq.maintenance.sla.vo.*;
import com.cq.maintenance.workorder.mapper.WorkOrderMapper.WorkOrderDataScope;
import java.time.LocalDateTime;
import java.util.List;
import org.apache.ibatis.annotations.*;

@Mapper
public interface SlaMapper extends BaseMapper<SlaRule> {
    String EVENT_FROM=" FROM mnt_sla_event se JOIN mnt_work_order wo ON wo.id=se.work_order_id JOIN eqp_equipment e ON e.id=wo.equipment_id JOIN org_station st ON st.id=e.station_id JOIN org_line l ON l.id=st.line_id JOIN org_workshop w ON w.id=l.workshop_id LEFT JOIN sys_user u ON u.id=se.escalated_to_user_id ";
    String EVENT_SCOPE="<if test='scope.allData == false'> AND (<if test='scope.workshopId != null'>w.id=#{scope.workshopId}</if><if test='scope.workshopId == null'>1=0</if><if test='scope.teamIds != null and scope.teamIds.size() > 0'> OR e.responsible_team_id IN <foreach collection='scope.teamIds' item='id' open='(' separator=',' close=')'>#{id}</foreach></if>)</if>";
    @Select("SELECT id,priority,response_minutes,resolve_minutes,enabled,updated_at FROM mnt_sla_rule ORDER BY FIELD(priority,'URGENT','IMPORTANT','NORMAL')") List<SlaRuleVO> findRules();
    @Select("SELECT id,priority,response_minutes,resolve_minutes,enabled,updated_at FROM mnt_sla_rule WHERE priority=#{priority} AND enabled=1") SlaRule findEnabledRule(RepairPriority priority);
    @Update("UPDATE mnt_sla_rule SET response_minutes=#{response},resolve_minutes=#{resolve},enabled=#{enabled} WHERE id=#{id}") int updateRule(@Param("id")Long id,@Param("response")Integer response,@Param("resolve")Integer resolve,@Param("enabled")Boolean enabled);
    @Update("UPDATE mnt_work_order SET sla_rule_id=#{ruleId},sla_response_deadline=DATE_ADD(created_at,INTERVAL #{response} MINUTE),sla_resolve_deadline=DATE_ADD(created_at,INTERVAL #{resolve} MINUTE) WHERE id=#{workOrderId} AND work_order_type='REPAIR' AND sla_rule_id IS NULL") int bindRule(@Param("workOrderId")Long workOrderId,@Param("ruleId")Long ruleId,@Param("response")Integer response,@Param("resolve")Integer resolve);

    @Select("SELECT wo.id work_order_id,wo.work_order_no,wo.sla_rule_id rule_id,'RESPONSE_TIMEOUT' event_type,wo.sla_response_deadline deadline,COALESCE(tl.id,wm.id) escalation_user_id,COALESCE(tl.real_name,wm.real_name) escalation_user_name FROM mnt_work_order wo JOIN eqp_equipment e ON e.id=wo.equipment_id JOIN org_station st ON st.id=e.station_id JOIN org_line l ON l.id=st.line_id JOIN org_workshop w ON w.id=l.workshop_id LEFT JOIN org_team t ON t.id=e.responsible_team_id LEFT JOIN sys_user tl ON tl.id=t.leader_id AND tl.status='ENABLED' AND EXISTS(SELECT 1 FROM sys_user_role ur JOIN sys_role r ON r.id=ur.role_id WHERE ur.user_id=tl.id AND r.role_code='MAINTENANCE_SUPERVISOR' AND r.status='ENABLED') LEFT JOIN sys_user wm ON wm.id=w.manager_id AND wm.status='ENABLED' AND EXISTS(SELECT 1 FROM sys_user_role ur JOIN sys_role r ON r.id=ur.role_id WHERE ur.user_id=wm.id AND r.role_code='MAINTENANCE_SUPERVISOR' AND r.status='ENABLED') WHERE wo.work_order_type='REPAIR' AND wo.status NOT IN ('COMPLETED','CANCELLED') AND wo.accepted_at IS NULL AND wo.sla_rule_id IS NOT NULL AND wo.sla_response_deadline<#{now}") List<SlaMonitorRow> findResponseTimeouts(LocalDateTime now);
    @Select("SELECT wo.id work_order_id,wo.work_order_no,wo.sla_rule_id rule_id,'RESOLVE_TIMEOUT' event_type,wo.sla_resolve_deadline deadline,COALESCE(tl.id,wm.id) escalation_user_id,COALESCE(tl.real_name,wm.real_name) escalation_user_name FROM mnt_work_order wo JOIN eqp_equipment e ON e.id=wo.equipment_id JOIN org_station st ON st.id=e.station_id JOIN org_line l ON l.id=st.line_id JOIN org_workshop w ON w.id=l.workshop_id LEFT JOIN org_team t ON t.id=e.responsible_team_id LEFT JOIN sys_user tl ON tl.id=t.leader_id AND tl.status='ENABLED' AND EXISTS(SELECT 1 FROM sys_user_role ur JOIN sys_role r ON r.id=ur.role_id WHERE ur.user_id=tl.id AND r.role_code='MAINTENANCE_SUPERVISOR' AND r.status='ENABLED') LEFT JOIN sys_user wm ON wm.id=w.manager_id AND wm.status='ENABLED' AND EXISTS(SELECT 1 FROM sys_user_role ur JOIN sys_role r ON r.id=ur.role_id WHERE ur.user_id=wm.id AND r.role_code='MAINTENANCE_SUPERVISOR' AND r.status='ENABLED') WHERE wo.work_order_type='REPAIR' AND wo.status NOT IN ('COMPLETED','CANCELLED') AND wo.sla_rule_id IS NOT NULL AND wo.sla_resolve_deadline<#{now}") List<SlaMonitorRow> findResolveTimeouts(LocalDateTime now);
    @Insert("INSERT IGNORE INTO mnt_sla_event(work_order_id,event_type,rule_id,occurred_at,escalated_to_user_id,handled,remark) VALUES(#{workOrderId},#{eventType},#{ruleId},#{occurredAt},#{escalatedToUserId},0,#{remark})") @Options(useGeneratedKeys=true,keyProperty="id") int insertEvent(SlaEvent event);
    @Update("UPDATE mnt_sla_event SET message_id=#{messageId} WHERE id=#{eventId} AND message_id IS NULL") int linkMessage(@Param("eventId")Long eventId,@Param("messageId")Long messageId);
    @Select("<script>SELECT se.id,se.work_order_id,wo.work_order_no,wo.priority,se.event_type,CASE WHEN se.event_type='RESPONSE_TIMEOUT' THEN wo.sla_response_deadline ELSE wo.sla_resolve_deadline END deadline,se.occurred_at,se.escalated_to_user_id,u.real_name escalated_to_user_name,se.handled,se.handled_at,se.remark"+EVENT_FROM+" WHERE 1=1 <if test='q.eventType != null'> AND se.event_type=#{q.eventType}</if><if test='q.handled != null'> AND se.handled=#{q.handled}</if> "+EVENT_SCOPE+" ORDER BY se.occurred_at DESC,se.id DESC LIMIT #{q.size} OFFSET #{q.offset}</script>") List<SlaEventVO> findEventPage(@Param("q")SlaEventQuery query,@Param("scope")WorkOrderDataScope scope);
    @Select("<script>SELECT COUNT(*)"+EVENT_FROM+" WHERE 1=1 <if test='q.eventType != null'> AND se.event_type=#{q.eventType}</if><if test='q.handled != null'> AND se.handled=#{q.handled}</if> "+EVENT_SCOPE+"</script>") long countEvents(@Param("q")SlaEventQuery query,@Param("scope")WorkOrderDataScope scope);
    @Select("<script>SELECT COUNT(*)"+EVENT_FROM+" WHERE se.id=#{id} "+EVENT_SCOPE+"</script>") long countEventVisible(@Param("id")Long id,@Param("scope")WorkOrderDataScope scope);
    @Update("UPDATE mnt_sla_event SET handled=1,handled_at=NOW() WHERE id=#{id} AND handled=0") int handle(Long id);
}
