<script setup lang="ts">
import { onBeforeUnmount, onMounted, shallowRef } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { ElMessage } from 'element-plus'
import * as api from '../../api/equipment'
import * as maintenanceApi from '../../api/maintenance'
import { useAuthStore } from '../../stores/auth'
import { workOrderStatusLabel, workOrderStatusType } from '../../utils/workOrderStatus'
import { statusLabel, statusTagType } from '../../utils/equipmentStatus'
const route=useRoute();const router=useRouter();const auth=useAuthStore();const loading=shallowRef(true);const detail=shallowRef<any>(null);const qrUrl=shallowRef('');const plans=shallowRef<any[]>([]);const maintenanceHistory=shallowRef<any[]>([])
async function load(){loading.value=true;try{const id=Number(route.params.id);detail.value=(await api.detail(id)).data;const requests:any[]=[api.qrCode(id)];if(auth.hasPermission('maintenance:history:view'))requests.push(api.maintenanceHistory(id));if(auth.hasPermission('maintenance:plan:list'))requests.push(maintenanceApi.page({equipmentId:id,page:1,size:100}));const results=await Promise.all(requests);qrUrl.value=URL.createObjectURL(results[0]);let index=1;if(auth.hasPermission('maintenance:history:view'))maintenanceHistory.value=results[index++].data;if(auth.hasPermission('maintenance:plan:list'))plans.value=results[index].data.records}catch(e:any){ElMessage.error(e.response?.data?.message||'设备详情加载失败')}finally{loading.value=false}}
onMounted(load);onBeforeUnmount(()=>{if(qrUrl.value)URL.revokeObjectURL(qrUrl.value)})
</script>
<template><section class="module-page" v-loading="loading"><header class="module-header"><div><p class="eyebrow">EQUIPMENT PROFILE</p><h1>{{detail?.equipmentName||'设备详情'}}</h1><p>{{detail?.equipmentNo}}</p></div><el-button @click="router.back()">返回列表</el-button></header>
<template v-if="detail"><div class="detail-grid"><el-card shadow="never"><template #header><div class="card-heading"><b>基础信息</b><el-button v-if="detail.status==='RUNNING'" v-permission="'repair:create'" type="danger" @click="router.push(`/repair-requests?equipmentId=${detail.id}`)">故障报修</el-button></div></template><el-descriptions :column="2" border><el-descriptions-item label="设备编号">{{detail.equipmentNo}}</el-descriptions-item><el-descriptions-item label="当前状态"><el-tag :type="statusTagType(detail.status)">{{statusLabel(detail.status)}}</el-tag></el-descriptions-item><el-descriptions-item label="设备类型">{{detail.typeName}}</el-descriptions-item><el-descriptions-item label="型号">{{detail.model||'-'}}</el-descriptions-item><el-descriptions-item label="厂商">{{detail.manufacturer||'-'}}</el-descriptions-item><el-descriptions-item label="累计运行">{{detail.runningHours}} 小时</el-descriptions-item><el-descriptions-item label="出厂日期">{{detail.manufactureDate||'-'}}</el-descriptions-item><el-descriptions-item label="启用日期">{{detail.commissioningDate||'-'}}</el-descriptions-item><el-descriptions-item label="保修到期">{{detail.warrantyExpireDate||'-'}}</el-descriptions-item><el-descriptions-item label="责任人">{{detail.responsibleUserName||'-'}}</el-descriptions-item><el-descriptions-item label="负责班组">{{detail.responsibleTeamName||'-'}}</el-descriptions-item><el-descriptions-item label="位置">{{detail.workshopName}} / {{detail.lineName}} / {{detail.stationName}}</el-descriptions-item><el-descriptions-item label="规格参数" :span="2">{{detail.specifications||'-'}}</el-descriptions-item></el-descriptions></el-card><el-card shadow="never" class="qr-card"><template #header><b>扫码报修二维码</b></template><img v-if="qrUrl" :src="qrUrl" alt="设备扫码报修二维码"><p>扫码打开 Web 报修页并自动带入当前设备，不包含用户凭据。</p></el-card></div>
<el-tabs type="border-card"><el-tab-pane label="状态履历"><el-timeline v-if="detail.statusHistory.length"><el-timeline-item v-for="i in detail.statusHistory" :key="i.id" :timestamp="i.changedAt" placement="top"><b>{{i.fromStatus?statusLabel(i.fromStatus):'建档'}} → {{statusLabel(i.toStatus)}}</b><p>{{i.reason||'未填写原因'}} · {{i.operatorName||`用户 ${i.operatorId}`}} · {{i.sourceType}}</p></el-timeline-item></el-timeline><el-empty v-else description="暂无状态履历"/></el-tab-pane><el-tab-pane v-if="auth.hasPermission('maintenance:plan:list')" label="保养计划"><el-table v-if="plans.length" :data="plans"><el-table-column prop="planNo" label="计划编号"/><el-table-column prop="planName" label="计划名称"/><el-table-column prop="nextExecuteDate" label="下次执行" width="120"/><el-table-column label="状态" width="90"><template #default="{row}"><el-tag :type="row.status==='ENABLED'?'success':'info'">{{row.status==='ENABLED'?'启用':'停用'}}</el-tag></template></el-table-column></el-table><el-empty v-else description="该设备尚未配置保养计划"/></el-tab-pane><el-tab-pane v-if="auth.hasPermission('maintenance:history:view')" label="保养记录"><el-table v-if="maintenanceHistory.length" :data="maintenanceHistory"><el-table-column prop="workOrderNo" label="工单编号" min-width="180"/><el-table-column prop="planName" label="保养计划" min-width="150"/><el-table-column label="状态" width="100"><template #default="{row}"><el-tag :type="workOrderStatusType(row.status)">{{workOrderStatusLabel(row.status)}}</el-tag></template></el-table-column><el-table-column prop="engineerName" label="执行人" width="110"/><el-table-column label="结果" width="130"><template #default="{row}">{{row.completedItems}} 项<span v-if="row.abnormalItems"> · {{row.abnormalItems}} 异常</span></template></el-table-column><el-table-column prop="completedAt" label="完成时间" width="168"><template #default="{row}">{{row.completedAt||'-'}}</template></el-table-column></el-table><el-empty v-else description="该设备暂无保养记录"/></el-tab-pane></el-tabs></template></section></template>
