<script setup lang="ts">
import { onBeforeUnmount, onMounted, shallowRef } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { ElMessage } from 'element-plus'
import * as api from '../../api/equipment'
import { statusLabel, statusTagType } from '../../utils/equipmentStatus'
const route=useRoute();const router=useRouter();const loading=shallowRef(true);const detail=shallowRef<any>(null);const qrUrl=shallowRef('')
async function load(){loading.value=true;try{const id=Number(route.params.id);detail.value=(await api.detail(id)).data;const blob=await api.qrCode(id);qrUrl.value=URL.createObjectURL(blob)}catch(e:any){ElMessage.error(e.response?.data?.message||'设备详情加载失败')}finally{loading.value=false}}
onMounted(load);onBeforeUnmount(()=>{if(qrUrl.value)URL.revokeObjectURL(qrUrl.value)})
</script>
<template><section class="module-page" v-loading="loading"><header class="module-header"><div><p class="eyebrow">EQUIPMENT PROFILE</p><h1>{{detail?.equipmentName||'设备详情'}}</h1><p>{{detail?.equipmentNo}}</p></div><el-button @click="router.back()">返回列表</el-button></header>
<template v-if="detail"><div class="detail-grid"><el-card shadow="never"><template #header><div class="card-heading"><b>基础信息</b><el-button v-if="detail.status==='RUNNING'" v-permission="'repair:create'" type="danger" @click="router.push(`/repair-requests?equipmentId=${detail.id}`)">故障报修</el-button></div></template><el-descriptions :column="2" border><el-descriptions-item label="设备编号">{{detail.equipmentNo}}</el-descriptions-item><el-descriptions-item label="当前状态"><el-tag :type="statusTagType(detail.status)">{{statusLabel(detail.status)}}</el-tag></el-descriptions-item><el-descriptions-item label="设备类型">{{detail.typeName}}</el-descriptions-item><el-descriptions-item label="型号">{{detail.model||'-'}}</el-descriptions-item><el-descriptions-item label="厂商">{{detail.manufacturer||'-'}}</el-descriptions-item><el-descriptions-item label="累计运行">{{detail.runningHours}} 小时</el-descriptions-item><el-descriptions-item label="出厂日期">{{detail.manufactureDate||'-'}}</el-descriptions-item><el-descriptions-item label="启用日期">{{detail.commissioningDate||'-'}}</el-descriptions-item><el-descriptions-item label="保修到期">{{detail.warrantyExpireDate||'-'}}</el-descriptions-item><el-descriptions-item label="责任人">{{detail.responsibleUserName||'-'}}</el-descriptions-item><el-descriptions-item label="负责班组">{{detail.responsibleTeamName||'-'}}</el-descriptions-item><el-descriptions-item label="位置">{{detail.workshopName}} / {{detail.lineName}} / {{detail.stationName}}</el-descriptions-item><el-descriptions-item label="规格参数" :span="2">{{detail.specifications||'-'}}</el-descriptions-item></el-descriptions></el-card><el-card shadow="never" class="qr-card"><template #header><b>扫码报修二维码</b></template><img v-if="qrUrl" :src="qrUrl" alt="设备扫码报修二维码"><p>扫码打开 Web 报修页并自动带入当前设备，不包含用户凭据。</p></el-card></div>
<el-card shadow="never"><template #header><b>状态履历</b></template><el-timeline v-if="detail.statusHistory.length"><el-timeline-item v-for="i in detail.statusHistory" :key="i.id" :timestamp="i.changedAt" placement="top"><b>{{i.fromStatus?statusLabel(i.fromStatus):'建档'}} → {{statusLabel(i.toStatus)}}</b><p>{{i.reason||'未填写原因'}} · {{i.operatorName||`用户 ${i.operatorId}`}} · {{i.sourceType}}</p></el-timeline-item></el-timeline><el-empty v-else description="暂无状态履历"/></el-card></template></section></template>
