package com.cq.maintenance;

import static org.junit.jupiter.api.Assertions.*;
import com.cq.maintenance.common.exception.BusinessException;import com.cq.maintenance.knowledge.dto.*;import com.cq.maintenance.knowledge.entity.KnowledgeStatus;import com.cq.maintenance.knowledge.service.*;import com.cq.maintenance.security.LoginUser;import java.time.LocalDateTime;import java.util.List;import org.junit.jupiter.api.*;import org.junit.jupiter.api.condition.EnabledIfSystemProperty;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.boot.test.context.SpringBootTest;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;import org.springframework.security.core.context.SecurityContextHolder;import org.springframework.test.context.ActiveProfiles;import org.springframework.test.context.TestPropertySource;import org.springframework.test.context.jdbc.Sql;import org.springframework.test.context.jdbc.SqlConfig;

@SpringBootTest(properties={"app.auth.jwt-secret=test-only-secret-that-is-at-least-32-bytes-long","app.maintenance.scan-cron=-","app.sla.scan-cron=-"})
@ActiveProfiles("local") @TestPropertySource(properties="stage10.db-tests=true")
@EnabledIfSystemProperty(named="stage10.db-tests",matches="true")
@Sql(scripts={"file:../sql/21_stage10_schema.sql","file:../sql/22_stage10_permissions.sql"}) @SqlConfig(encoding="UTF-8")
class Stage10DatabaseIntegrationTest {
    @Autowired JdbcTemplate jdbc;@Autowired KnowledgeService knowledge;@Autowired SimilarWorkOrderService similar;
    @AfterEach void clear(){SecurityContextHolder.clearContext();}
    Long user(String name){return jdbc.queryForObject("SELECT id FROM sys_user WHERE username=?",Long.class,name);}Long workshop(){return jdbc.queryForObject("SELECT id FROM org_workshop WHERE workshop_no='WS-01'",Long.class);}Long team(){return jdbc.queryForObject("SELECT id FROM org_team WHERE team_no='TEAM-01'",Long.class);}
    void login(String name,String role){Long id=user(name);LoginUser value=new LoginUser(id,name,name,"ENABLED",List.of(role),List.of(),role.equals("ENGINEER")||role.equals("MAINTENANCE_SUPERVISOR")?List.of(team()):List.of(),role.equals("ADMIN")?null:workshop(),List.of());SecurityContextHolder.getContext().setAuthentication(UsernamePasswordAuthenticationToken.authenticated(value,null,List.of()));}
    Long completedRepair(String fault,String root,String action,String result){String suffix=Long.toString(System.nanoTime());Long type=jdbc.queryForObject("SELECT id FROM eqp_type WHERE type_code='CNC'",Long.class);Long station=jdbc.queryForObject("SELECT id FROM org_station WHERE station_no='ST-01'",Long.class);jdbc.update("INSERT INTO eqp_equipment(equipment_no,equipment_name,type_id,station_id,responsible_team_id,status,qr_code) VALUES(?,?,?,?,?,'RUNNING',?)","S10-E"+suffix,"第10阶段数控机床",type,station,team(),"S10-Q"+suffix);Long equipment=jdbc.queryForObject("SELECT id FROM eqp_equipment WHERE equipment_no=?",Long.class,"S10-E"+suffix);jdbc.update("INSERT INTO mnt_repair_request(request_no,equipment_id,reporter_id,source,priority,fault_description,status) VALUES(?,?,?,'PC','NORMAL',?,'CONVERTED')","S10-R"+suffix,equipment,user("reporter"),fault);Long request=jdbc.queryForObject("SELECT id FROM mnt_repair_request WHERE request_no=?",Long.class,"S10-R"+suffix);jdbc.update("INSERT INTO mnt_work_order(work_order_no,work_order_type,repair_request_id,equipment_id,priority,status,assigned_engineer_id,assigned_team_id,created_by,completed_at) VALUES(?,'REPAIR',?,?,'NORMAL','COMPLETED',?,?,?,?)","S10-W"+suffix,request,equipment,user("engineer"),team(),user("reporter"),LocalDateTime.now());Long order=jdbc.queryForObject("SELECT id FROM mnt_work_order WHERE work_order_no=?",Long.class,"S10-W"+suffix);jdbc.update("INSERT INTO mnt_repair_record(work_order_id,inspection_process,root_cause,repair_action,repair_result,labor_hours,downtime_minutes,repairable,created_by) VALUES(?,?,?,?,?,1,20,1,?)",order,"现场检测与拆检",root,action,result,user("engineer"));return order;}
    @Test void schemaAndPermissionsExist(){assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='kb_article' AND COLUMN_NAME='repair_result'",Integer.class));assertTrue(jdbc.queryForObject("SELECT COUNT(*) FROM sys_menu WHERE permission_code LIKE 'knowledge:%'",Integer.class)>=6);}
    @Test void rolePermissionsFollowKnowledgeResponsibility(){assertTrue(hasPermission("ADMIN","knowledge:audit"));assertTrue(hasPermission("MAINTENANCE_SUPERVISOR","knowledge:audit"));assertTrue(hasPermission("ENGINEER","knowledge:create"));assertFalse(hasPermission("ENGINEER","knowledge:audit"));assertFalse(hasPermission("WAREHOUSE_ADMIN","knowledge:audit"));assertFalse(hasPermission("REPORTER","knowledge:create"));assertFalse(hasPermission("REPORTER","knowledge:update"));assertTrue(hasPermission("REPORTER","workorder:similar"));}
    boolean hasPermission(String role,String permission){return jdbc.queryForObject("SELECT COUNT(*) FROM sys_role_menu rm JOIN sys_role r ON r.id=rm.role_id JOIN sys_menu m ON m.id=rm.menu_id WHERE r.role_code=? AND m.permission_code=?",Integer.class,role,permission)>0;}
    @Test void completedRepairFormsReviewedKnowledgeClosure(){Long order=completedRepair("主轴轴承持续异响并伴随温升","主轴轴承磨损","更换主轴轴承并重新润滑","试运行两小时正常");login("engineer","ENGINEER");Long article=knowledge.createFromWorkOrder(order);var draft=knowledge.detail(article);assertEquals(KnowledgeStatus.DRAFT,draft.status());assertEquals("主轴轴承磨损",draft.rootCause());assertEquals("试运行两小时正常",draft.repairResult());knowledge.update(article,new KnowledgeArticleRequest("主轴轴承异响维修经验",draft.faultSymptom(),draft.rootCause(),draft.solution(),draft.repairResult()));knowledge.submit(article);login("supervisor","MAINTENANCE_SUPERVISOR");knowledge.review(article,new KnowledgeReviewRequest(true,"内容完整，可发布"));assertEquals("PUBLISHED",jdbc.queryForObject("SELECT status FROM kb_article WHERE id=?",String.class,article));assertEquals(user("supervisor"),jdbc.queryForObject("SELECT reviewed_by FROM kb_article WHERE id=?",Long.class,article));}
    @Test void rejectionPersistsReviewerAndRemark(){Long order=completedRepair("伺服电机报警无法启动","接线松动","紧固接线","恢复启动");login("engineer","ENGINEER");Long article=knowledge.createFromWorkOrder(order);knowledge.submit(article);login("supervisor","MAINTENANCE_SUPERVISOR");knowledge.review(article,new KnowledgeReviewRequest(false,"请补充排查步骤"));assertEquals("REJECTED",jdbc.queryForObject("SELECT status FROM kb_article WHERE id=?",String.class,article));assertEquals("请补充排查步骤",jdbc.queryForObject("SELECT review_remark FROM kb_article WHERE id=?",String.class,article));}
    @Test void oneCompletedRepairCannotCreateDuplicateKnowledge(){Long order=completedRepair("液压泵漏油","密封圈老化","更换密封圈","无泄漏");login("engineer","ENGINEER");knowledge.createFromWorkOrder(order);assertThrows(BusinessException.class,()->knowledge.createFromWorkOrder(order));}
    @Test void realIssuedSpareIsCopiedWithoutChangingInventory(){Long order=completedRepair("主轴轴承磨损异响","润滑不足导致磨损","更换轴承并润滑","试运行正常");Long equipment=jdbc.queryForObject("SELECT equipment_id FROM mnt_work_order WHERE id=?",Long.class,order);Long warehouse=jdbc.queryForObject("SELECT id FROM inv_warehouse ORDER BY id LIMIT 1",Long.class);Long spare=jdbc.queryForObject("SELECT id FROM inv_spare_part ORDER BY id LIMIT 1",Long.class);String no="S10-T"+System.nanoTime();jdbc.update("INSERT INTO inv_transaction(transaction_no,warehouse_id,spare_part_id,transaction_type,qty_change,qty_before,qty_after,unit_price,work_order_id,equipment_id,operator_id,remark) VALUES(?,?,?,'ISSUE',-2,20,18,10,?,?,?,'第10阶段知识备件验证')",no,warehouse,spare,order,equipment,user("engineer"));Long transaction=jdbc.queryForObject("SELECT id FROM inv_transaction WHERE transaction_no=?",Long.class,no);jdbc.update("INSERT INTO inv_work_order_spare(work_order_id,warehouse_id,spare_part_id,qty,unit_price_snapshot,transaction_id,status,issued_by) VALUES(?,?,?,2,10,?,'ISSUED',?)",order,warehouse,spare,transaction,user("engineer"));login("engineer","ENGINEER");Long article=knowledge.createFromWorkOrder(order);assertNotNull(knowledge.detail(article).spareSummary());assertTrue(knowledge.detail(article).spareSummary().contains("× 2"));assertEquals(2,jdbc.queryForObject("SELECT qty FROM inv_work_order_spare WHERE transaction_id=?",Integer.class,transaction));}
    @Test void unfinishedAndMaintenanceOrdersAreNotKnowledgeSources(){String suffix=Long.toString(System.nanoTime());Long equipment=jdbc.queryForObject("SELECT id FROM eqp_equipment WHERE status='RUNNING' LIMIT 1",Long.class);jdbc.update("INSERT INTO pm_plan(plan_no,plan_name,equipment_id,cycle_type,cycle_value,next_execute_date,status) VALUES(?, '第10阶段测试计划',?,'MONTH',1,CURRENT_DATE,'ENABLED')","S10-P"+suffix,equipment);Long plan=jdbc.queryForObject("SELECT id FROM pm_plan WHERE plan_no=?",Long.class,"S10-P"+suffix);jdbc.update("INSERT INTO mnt_work_order(work_order_no,work_order_type,pm_plan_id,equipment_id,priority,status,assigned_engineer_id,assigned_team_id,created_by,completed_at) VALUES(?,'MAINTENANCE',?,?,'NORMAL','COMPLETED',?,?,?,NOW())","S10-PM"+suffix,plan,equipment,user("engineer"),team(),user("engineer"));Long order=jdbc.queryForObject("SELECT id FROM mnt_work_order WHERE work_order_no=?",Long.class,"S10-PM"+suffix);login("engineer","ENGINEER");assertThrows(BusinessException.class,()->knowledge.createFromWorkOrder(order));}
    @Test void realCorpusReturnsStablePositiveTopFive(){String[] faults={"主轴轴承异响并伴随振动","主轴轴承温度过高","主轴高速旋转产生异响","液压管路漏油","伺服驱动器报警","主轴轴承振动过大"};for(String fault:faults)completedRepair(fault,"测试根因","测试处理","测试结果");login("engineer","ENGINEER");var first=similar.byDescription("主轴轴承异响振动");var second=similar.byDescription("主轴轴承异响振动");assertEquals(5,first.size());assertEquals(first,second);assertTrue(first.stream().allMatch(item->item.similarity()>0D));assertTrue(first.get(0).similarity()>=first.get(1).similarity());}
}
