package com.cq.maintenance;

import static org.junit.jupiter.api.Assertions.*;
import com.cq.maintenance.dispatch.service.DispatchRecommendationService;import com.cq.maintenance.notification.service.NotificationService;import com.cq.maintenance.repair.dto.RepairRequestCreateRequest;import com.cq.maintenance.repair.entity.*;import com.cq.maintenance.repair.service.RepairRequestService;import com.cq.maintenance.security.LoginUser;import com.cq.maintenance.sla.service.SlaService;import com.cq.maintenance.workorder.entity.WorkOrderStatus;import java.time.LocalDateTime;import java.util.List;import org.junit.jupiter.api.*;import org.junit.jupiter.api.condition.EnabledIfSystemProperty;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.boot.test.context.SpringBootTest;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;import org.springframework.security.core.context.SecurityContextHolder;import org.springframework.test.context.ActiveProfiles;import org.springframework.test.context.TestPropertySource;import org.springframework.test.context.jdbc.Sql;import org.springframework.test.context.jdbc.SqlConfig;

@SpringBootTest(properties={"app.auth.jwt-secret=test-only-secret-that-is-at-least-32-bytes-long","app.maintenance.scan-cron=-"})
@ActiveProfiles("local") @TestPropertySource(properties="stage9.db-tests=true")
@EnabledIfSystemProperty(named="stage9.db-tests",matches="true")
@Sql(scripts={"file:../sql/18_stage9_schema.sql","file:../sql/19_stage9_permissions.sql","file:../sql/20_stage9_demo_data.sql"})
@SqlConfig(encoding="UTF-8")
class Stage9DatabaseIntegrationTest {
    @Autowired JdbcTemplate jdbc;@Autowired RepairRequestService repairs;@Autowired DispatchRecommendationService recommendations;@Autowired SlaService sla;@Autowired NotificationService notifications;
    @AfterEach void clear(){SecurityContextHolder.clearContext();}
    Long user(String name){return jdbc.queryForObject("SELECT id FROM sys_user WHERE username=?",Long.class,name);}Long workshop(){return jdbc.queryForObject("SELECT id FROM org_workshop WHERE workshop_no='WS-01'",Long.class);}Long team(){return jdbc.queryForObject("SELECT id FROM org_team WHERE team_no='TEAM-01'",Long.class);}
    void login(String name,String role){Long id=user(name);login(id,name,role,role.equals("ADMIN")?null:workshop(),role.equals("MAINTENANCE_SUPERVISOR")?List.of(team()):List.of());}void login(Long id,String name,String role,Long workshop,List<Long> teams){LoginUser u=new LoginUser(id,name,name,"ENABLED",List.of(role),List.of(),teams,workshop,List.of());SecurityContextHolder.getContext().setAuthentication(UsernamePasswordAuthenticationToken.authenticated(u,null,List.of()));}
    Long runningEquipment(String suffix){Long type=jdbc.queryForObject("SELECT id FROM eqp_type WHERE type_code='CNC'",Long.class);Long station=jdbc.queryForObject("SELECT id FROM org_station WHERE station_no='ST-01'",Long.class);jdbc.update("INSERT INTO eqp_equipment(equipment_no,equipment_name,type_id,station_id,responsible_team_id,status,qr_code) VALUES(?,?,?,?,?,'RUNNING',?)","S9-"+suffix,"第9阶段设备",type,station,team(),"S9-QR-"+suffix);return jdbc.queryForObject("SELECT id FROM eqp_equipment WHERE equipment_no=?",Long.class,"S9-"+suffix);}
    @Test void schemaAndPermissionsExist(){assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='eqp_type_skill'",Integer.class));assertTrue(jdbc.queryForObject("SELECT COUNT(*) FROM sys_menu WHERE permission_code LIKE 'sla:%'",Integer.class)>=4);}
    @Test void repairCreationBindsFrozenSlaAndMaintenanceDoesNot(){login("reporter","REPORTER");var created=repairs.create(new RepairRequestCreateRequest(runningEquipment("SLA"+System.nanoTime()),RepairPriority.URGENT,"主轴报警",RepairSource.PC));assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM mnt_work_order WHERE id=? AND sla_rule_id IS NOT NULL AND sla_response_deadline=DATE_ADD(created_at,INTERVAL 30 MINUTE) AND sla_resolve_deadline=DATE_ADD(created_at,INTERVAL 240 MINUTE)",Integer.class,created.workOrderId()));}
    @Test void recommendationsUseThreeRealEngineersAndStayReadOnly(){login("supervisor","MAINTENANCE_SUPERVISOR");Long id=repairs.create(new RepairRequestCreateRequest(runningEquipment("REC"+System.nanoTime()),RepairPriority.IMPORTANT,"数控主轴异常",RepairSource.PC)).workOrderId();long before=jdbc.queryForObject("SELECT COUNT(*) FROM mnt_work_order_flow WHERE work_order_id=?",Long.class,id);var result=recommendations.recommend(id);assertEquals(3,result.size());assertEquals(before,jdbc.queryForObject("SELECT COUNT(*) FROM mnt_work_order_flow WHERE work_order_id=?",Long.class,id));assertEquals(WorkOrderStatus.PENDING_ASSIGN,jdbc.queryForObject("SELECT status FROM mnt_work_order WHERE id=?",WorkOrderStatus.class,id));}
    @Test void timeoutScanCreatesOneEventAndOneMessage(){login("reporter","REPORTER");Long id=repairs.create(new RepairRequestCreateRequest(runningEquipment("TIME"+System.nanoTime()),RepairPriority.URGENT,"紧急停机",RepairSource.PC)).workOrderId();jdbc.update("UPDATE mnt_work_order SET sla_response_deadline=? WHERE id=?",LocalDateTime.now().minusMinutes(1),id);sla.scanNow();sla.scanNow();assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM mnt_sla_event WHERE work_order_id=? AND event_type='RESPONSE_TIMEOUT'",Integer.class,id));assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM msg_notification n JOIN mnt_sla_event e ON e.message_id=n.id WHERE e.work_order_id=?",Integer.class,id));}
    @Test void responseAndTerminalStatesStopTheirSlaScans(){login("reporter","REPORTER");Long responded=repairs.create(new RepairRequestCreateRequest(runningEquipment("RESP"+System.nanoTime()),RepairPriority.URGENT,"已响应但未解决",RepairSource.PC)).workOrderId();jdbc.update("UPDATE mnt_work_order SET accepted_at=?,sla_response_deadline=?,sla_resolve_deadline=? WHERE id=?",LocalDateTime.now(),LocalDateTime.now().minusMinutes(2),LocalDateTime.now().minusMinutes(1),responded);sla.scanNow();assertEquals(0,jdbc.queryForObject("SELECT COUNT(*) FROM mnt_sla_event WHERE work_order_id=? AND event_type='RESPONSE_TIMEOUT'",Integer.class,responded));assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM mnt_sla_event WHERE work_order_id=? AND event_type='RESOLVE_TIMEOUT'",Integer.class,responded));Long completed=repairs.create(new RepairRequestCreateRequest(runningEquipment("DONE"+System.nanoTime()),RepairPriority.URGENT,"已完成工单",RepairSource.PC)).workOrderId();jdbc.update("UPDATE mnt_work_order SET status='COMPLETED',completed_at=?,sla_response_deadline=?,sla_resolve_deadline=? WHERE id=?",LocalDateTime.now(),LocalDateTime.now().minusMinutes(2),LocalDateTime.now().minusMinutes(1),completed);sla.scanNow();assertEquals(0,jdbc.queryForObject("SELECT COUNT(*) FROM mnt_sla_event WHERE work_order_id=?",Integer.class,completed));}
    @Test void notificationOwnershipAndReadStateAreEnforced(){Long receiver=user("supervisor");jdbc.update("INSERT INTO msg_notification(receiver_id,message_type,title,content,business_type,business_id,is_read) VALUES(?,'SLA','测试','测试消息','WORK_ORDER',1,0)",receiver);Long message=jdbc.queryForObject("SELECT MAX(id) FROM msg_notification WHERE receiver_id=?",Long.class,receiver);login("engineer","ENGINEER");assertThrows(RuntimeException.class,()->notifications.read(message));login("supervisor","MAINTENANCE_SUPERVISOR");notifications.read(message);assertEquals(1,jdbc.queryForObject("SELECT is_read FROM msg_notification WHERE id=?",Integer.class,message));}
}
