package com.cq.maintenance;

import static org.junit.jupiter.api.Assertions.*;
import com.cq.maintenance.repair.dto.RepairRequestCreateRequest;import com.cq.maintenance.repair.entity.*;import com.cq.maintenance.repair.service.RepairRequestService;import com.cq.maintenance.security.LoginUser;import com.cq.maintenance.workorder.dto.*;import com.cq.maintenance.workorder.entity.WorkOrderStatus;import com.cq.maintenance.workorder.service.WorkOrderService;import java.math.BigDecimal;import java.nio.charset.StandardCharsets;import java.util.*;import javax.sql.DataSource;import org.junit.jupiter.api.*;import org.junit.jupiter.api.condition.EnabledIfSystemProperty;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.boot.test.context.SpringBootTest;import org.springframework.core.io.FileSystemResource;import org.springframework.core.io.support.EncodedResource;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.jdbc.datasource.init.ScriptUtils;import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;import org.springframework.security.core.context.SecurityContextHolder;import org.springframework.test.context.ActiveProfiles;

@SpringBootTest(properties="app.auth.jwt-secret=test-only-secret-that-is-at-least-32-bytes-long")
@ActiveProfiles("local") @EnabledIfSystemProperty(named="stage5.db-tests",matches="true")
@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
class Stage5DatabaseIntegrationTest {
    @Autowired DataSource dataSource;@Autowired JdbcTemplate jdbc;@Autowired RepairRequestService repairs;@Autowired WorkOrderService orders;
    @BeforeAll static void seed(@Autowired DataSource ds)throws Exception{try(var c=ds.getConnection()){for(String path:List.of("../sql/11_dev_auth_seed.sql","../sql/12_stage4_permissions.sql","../sql/13_stage4_demo_data.sql","../sql/14_stage5_permissions.sql"))ScriptUtils.executeSqlScript(c,new EncodedResource(new FileSystemResource(path),StandardCharsets.UTF_8));}}
    @AfterEach void clear(){SecurityContextHolder.clearContext();}
    Long user(String username){return jdbc.queryForObject("SELECT id FROM sys_user WHERE username=?",Long.class,username);}
    Long team(){return jdbc.queryForObject("SELECT id FROM org_team WHERE team_no='TEAM-01'",Long.class);}
    Long workshop(){return jdbc.queryForObject("SELECT id FROM org_workshop WHERE workshop_no='WS-01'",Long.class);}
    void login(String username,String role){Long id=user(username);Long teamId="engineer".equals(username)||"supervisor".equals(username)?team():null;Long workshopId="supervisor".equals(username)?workshop():null;LoginUser u=new LoginUser(id,username,username,"ENABLED",List.of(role),List.of(),teamId==null?List.of():List.of(teamId),workshopId,List.of());SecurityContextHolder.getContext().setAuthentication(UsernamePasswordAuthenticationToken.authenticated(u,null,List.of()));}
    Long createRunningEquipment(String suffix){String no="IT5-EQP-"+suffix+System.nanoTime();jdbc.update("INSERT INTO eqp_equipment(equipment_no,equipment_name,type_id,responsible_user_id,responsible_team_id,station_id,status,running_hours,qr_code) SELECT ?,?,t.id,u.id,tm.id,s.id,'RUNNING',0,? FROM eqp_type t JOIN sys_user u ON u.username='engineer' JOIN org_team tm ON tm.team_no='TEAM-01' JOIN org_station s ON s.station_no='ST-01' WHERE t.type_code='CNC'",no,"第5阶段事务测试设备",UUID.randomUUID().toString());Long id=jdbc.queryForObject("SELECT id FROM eqp_equipment WHERE equipment_no=?",Long.class,no);jdbc.update("INSERT INTO eqp_status_log(equipment_id,from_status,to_status,source_type,reason,operator_id) VALUES(?,NULL,'RUNNING','MANUAL','第5阶段测试数据',?)",id,user("admin"));return id;}
    long createToAcceptance(String suffix){Long equipmentId=createRunningEquipment(suffix);login("reporter","REPORTER");var created=repairs.create(new RepairRequestCreateRequest(equipmentId,RepairPriority.IMPORTANT,"主轴异常振动",RepairSource.PC));assertEquals("FAULT",jdbc.queryForObject("SELECT status FROM eqp_equipment WHERE id=?",String.class,equipmentId));assertEquals("PENDING_ASSIGN",jdbc.queryForObject("SELECT status FROM mnt_work_order WHERE id=?",String.class,created.workOrderId()));login("supervisor","MAINTENANCE_SUPERVISOR");orders.assign(created.workOrderId(),new DispatchRequest(user("engineer"),team(),"人工派单测试"));login("engineer","ENGINEER");orders.acceptResponse(created.workOrderId());orders.start(created.workOrderId());assertEquals("REPAIRING",jdbc.queryForObject("SELECT status FROM eqp_equipment WHERE id=?",String.class,equipmentId));orders.saveRepairRecord(created.workOrderId(),new RepairRecordRequest("检查传动机构","轴承磨损","更换轴承并校准","试运行正常",new BigDecimal("1.50"),120,true));orders.submitAcceptance(created.workOrderId());assertEquals("PENDING_ACCEPT",jdbc.queryForObject("SELECT status FROM mnt_work_order WHERE id=?",String.class,created.workOrderId()));return created.workOrderId();}
    @Test @Order(1) void completeRepairWorkflowPersistsBothStateHistories(){long id=createToAcceptance("MAIN-");Long equipmentId=jdbc.queryForObject("SELECT equipment_id FROM mnt_work_order WHERE id=?",Long.class,id);login("reporter","REPORTER");orders.pass(id,new AcceptanceRequest("试运行正常，验收通过"));assertEquals("COMPLETED",jdbc.queryForObject("SELECT status FROM mnt_work_order WHERE id=?",String.class,id));assertEquals("RUNNING",jdbc.queryForObject("SELECT status FROM eqp_equipment WHERE id=?",String.class,equipmentId));assertEquals(6,jdbc.queryForObject("SELECT COUNT(*) FROM mnt_work_order_flow WHERE work_order_id=?",Integer.class,id));assertTrue(jdbc.queryForObject("SELECT COUNT(*) FROM eqp_status_log WHERE equipment_id=? AND source_type='WORK_ORDER'",Integer.class,equipmentId)>=3);}
    @Test @Order(2) void rejectedAcceptanceReturnsToProcessingThenCanComplete(){long id=createToAcceptance("RETURN-");Long equipmentId=jdbc.queryForObject("SELECT equipment_id FROM mnt_work_order WHERE id=?",Long.class,id);login("reporter","REPORTER");orders.reject(id,new ReasonRequest("仍有轻微异响"));assertEquals("PROCESSING",jdbc.queryForObject("SELECT status FROM mnt_work_order WHERE id=?",String.class,id));assertEquals("REPAIRING",jdbc.queryForObject("SELECT status FROM eqp_equipment WHERE id=?",String.class,equipmentId));login("engineer","ENGINEER");orders.saveRepairRecord(id,new RepairRecordRequest("复检传动机构","联轴器偏移","重新对中","复检正常",new BigDecimal("2.00"),160,true));orders.submitAcceptance(id);login("reporter","REPORTER");orders.pass(id,new AcceptanceRequest("复检通过"));assertEquals(1,jdbc.queryForObject("SELECT acceptance_return_count FROM mnt_work_order WHERE id=?",Integer.class,id));assertEquals("COMPLETED",jdbc.queryForObject("SELECT status FROM mnt_work_order WHERE id=?",String.class,id));}
    @Test @Order(3) void reporterCanCancelPendingOrderAndExplicitlyStopEquipment(){Long equipmentId=createRunningEquipment("CANCEL-");login("reporter","REPORTER");var created=repairs.create(new RepairRequestCreateRequest(equipmentId,RepairPriority.NORMAL,"现场确认误报，但设备需停用检查",RepairSource.PC));repairs.cancel(created.repairRequestId(),new CancelWorkOrderRequest("误报后转停用检查",com.cq.maintenance.equipment.entity.EquipmentStatus.STOPPED));assertEquals("CANCELLED",jdbc.queryForObject("SELECT status FROM mnt_repair_request WHERE id=?",String.class,created.repairRequestId()));assertEquals("CANCELLED",jdbc.queryForObject("SELECT status FROM mnt_work_order WHERE id=?",String.class,created.workOrderId()));assertEquals("STOPPED",jdbc.queryForObject("SELECT status FROM eqp_equipment WHERE id=?",String.class,equipmentId));assertEquals(1,jdbc.queryForObject("SELECT COUNT(*) FROM eqp_status_log WHERE equipment_id=? AND from_status='FAULT' AND to_status='STOPPED' AND source_type='WORK_ORDER'",Integer.class,equipmentId));}
    @Test @Order(4) void actualDatabaseContainsRequiredStage5TablesAndUniqueRelation(){Integer count=jdbc.queryForObject("SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name IN ('mnt_repair_request','mnt_work_order','mnt_repair_record','mnt_work_order_flow','mnt_work_order_attachment','sys_user','org_team','eqp_equipment','eqp_status_log')",Integer.class);assertEquals(9,count);Integer unique=jdbc.queryForObject("SELECT COUNT(*) FROM information_schema.statistics WHERE table_schema=DATABASE() AND table_name='mnt_work_order' AND index_name='uk_work_order_repair_request' AND non_unique=0",Integer.class);assertEquals(1,unique);}
}
