package com.cq.maintenance.inventory.mapper;

import com.baomidou.mybatisplus.core.mapper.BaseMapper;
import com.cq.maintenance.inventory.dto.*;
import com.cq.maintenance.inventory.entity.*;
import com.cq.maintenance.inventory.vo.*;
import com.cq.maintenance.system.vo.UserSummaryVO;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.*;

@Mapper
public interface InventoryMapper extends BaseMapper<Warehouse> {
    String WAREHOUSE_SCOPE="<if test='allData == false'> AND w.id IN <foreach collection='warehouseIds' item='wid' open='(' separator=',' close=')'>#{wid}</foreach></if>";
    String WARNING_SCOPE="<if test='allData == false'> AND v.warehouse_id IN <foreach collection='warehouseIds' item='wid' open='(' separator=',' close=')'>#{wid}</foreach></if>";
    String STOCK_FROM=" FROM inv_stock s JOIN inv_warehouse w ON w.id=s.warehouse_id JOIN inv_spare_part p ON p.id=s.spare_part_id "+
        "LEFT JOIN (SELECT warehouse_id,spare_part_id,GREATEST(0,-SUM(qty_change))/30 daily_qty FROM inv_transaction WHERE created_at&gt;=DATE_SUB(NOW(),INTERVAL 30 DAY) AND transaction_type IN ('OUTBOUND','ISSUE','RETURN','SCRAP') GROUP BY warehouse_id,spare_part_id) c ON c.warehouse_id=s.warehouse_id AND c.spare_part_id=s.spare_part_id ";
    String STOCK_WHERE="<where>1=1 <if test='q.warehouseId != null'> AND s.warehouse_id=#{q.warehouseId}</if><if test='q.sparePartId != null'> AND s.spare_part_id=#{q.sparePartId}</if><if test='q.keyword != null and q.keyword != &quot;&quot;'> AND (p.spare_no LIKE CONCAT('%',#{q.keyword},'%') OR p.spare_name LIKE CONCAT('%',#{q.keyword},'%'))</if>"+
        "<if test='q.lowStockOnly == true'> AND s.current_qty &lt; ROUND(COALESCE(c.daily_qty,0)*p.safety_days,2)</if>"+WAREHOUSE_SCOPE+"</where>";
    String TX_FROM=" FROM inv_transaction t JOIN inv_warehouse w ON w.id=t.warehouse_id JOIN inv_spare_part p ON p.id=t.spare_part_id LEFT JOIN mnt_work_order wo ON wo.id=t.work_order_id LEFT JOIN eqp_equipment e ON e.id=t.equipment_id LEFT JOIN sys_user u ON u.id=t.operator_id ";
    String TX_WHERE="<where>1=1 <if test='q.warehouseId != null'> AND t.warehouse_id=#{q.warehouseId}</if><if test='q.sparePartId != null'> AND t.spare_part_id=#{q.sparePartId}</if><if test='q.transactionType != null and q.transactionType != &quot;&quot;'> AND t.transaction_type=#{q.transactionType}</if><if test='q.workOrderId != null'> AND t.work_order_id=#{q.workOrderId}</if><if test='q.startDate != null'> AND DATE(t.created_at)&gt;=#{q.startDate}</if><if test='q.endDate != null'> AND DATE(t.created_at)&lt;=#{q.endDate}</if>"+WAREHOUSE_SCOPE+"</where>";

    @Select("<script>SELECT w.id,w.warehouse_no,w.warehouse_name,w.location,w.manager_id,u.real_name manager_name,w.status,w.created_at,w.updated_at FROM inv_warehouse w LEFT JOIN sys_user u ON u.id=w.manager_id <where>1=1 <if test='q.keyword != null and q.keyword != &quot;&quot;'> AND (w.warehouse_no LIKE CONCAT('%',#{q.keyword},'%') OR w.warehouse_name LIKE CONCAT('%',#{q.keyword},'%') OR w.location LIKE CONCAT('%',#{q.keyword},'%'))</if><if test='q.status != null and q.status != &quot;&quot;'> AND w.status=#{q.status}</if>"+WAREHOUSE_SCOPE+"</where> ORDER BY w.id DESC LIMIT #{q.size} OFFSET #{q.offset}</script>")
    List<WarehouseRowVO> findWarehousePage(@Param("q") WarehouseQuery q,@Param("allData") boolean allData,@Param("warehouseIds") List<Long> warehouseIds);
    @Select("<script>SELECT COUNT(*) FROM inv_warehouse w <where>1=1 <if test='q.keyword != null and q.keyword != &quot;&quot;'> AND (w.warehouse_no LIKE CONCAT('%',#{q.keyword},'%') OR w.warehouse_name LIKE CONCAT('%',#{q.keyword},'%') OR w.location LIKE CONCAT('%',#{q.keyword},'%'))</if><if test='q.status != null and q.status != &quot;&quot;'> AND w.status=#{q.status}</if>"+WAREHOUSE_SCOPE+"</where></script>")
    long countWarehousePage(@Param("q") WarehouseQuery q,@Param("allData") boolean allData,@Param("warehouseIds") List<Long> warehouseIds);
    @Select("SELECT id,warehouse_no,warehouse_name,location,manager_id,status,created_at,updated_at FROM inv_warehouse WHERE id=#{id}") Warehouse findWarehouse(Long id);
    @Select("SELECT w.id,w.warehouse_no,w.warehouse_name,w.location,w.manager_id,u.real_name manager_name,w.status,w.created_at,w.updated_at FROM inv_warehouse w LEFT JOIN sys_user u ON u.id=w.manager_id WHERE w.id=#{id}") WarehouseRowVO findWarehouseRow(Long id);
    @Select("SELECT COUNT(*) FROM inv_warehouse WHERE warehouse_no=#{code} AND (#{excludeId} IS NULL OR id<>#{excludeId})") long countWarehouseCode(@Param("code") String code,@Param("excludeId") Long excludeId);
    @Select("SELECT COUNT(*) FROM sys_user WHERE id=#{id} AND status='ENABLED'") long countEnabledUser(Long id);
    @Select("SELECT COUNT(*) FROM sys_user u WHERE u.id=#{id} AND u.status='ENABLED' AND EXISTS(SELECT 1 FROM sys_user_role ur JOIN sys_role r ON r.id=ur.role_id WHERE ur.user_id=u.id AND r.role_code IN ('WAREHOUSE_ADMIN','ENGINEER'))") long countWarehouseAssignableUser(Long id);
    @Insert("INSERT INTO inv_warehouse(warehouse_no,warehouse_name,location,manager_id,status) VALUES(#{warehouseNo},#{warehouseName},#{location},#{managerId},#{status})") @Options(useGeneratedKeys=true,keyProperty="id") int insertWarehouse(Warehouse warehouse);
    @Update("UPDATE inv_warehouse SET warehouse_no=#{warehouseNo},warehouse_name=#{warehouseName},location=#{location},manager_id=#{managerId},status=#{status} WHERE id=#{id}") int updateWarehouse(Warehouse warehouse);
    @Select("SELECT user_id FROM inv_warehouse_user WHERE warehouse_id=#{warehouseId} ORDER BY user_id") List<Long> findAuthorizedUserIds(Long warehouseId);
    @Delete("DELETE FROM inv_warehouse_user WHERE warehouse_id=#{warehouseId}") int clearWarehouseUsers(Long warehouseId);
    @Insert("<script>INSERT INTO inv_warehouse_user(warehouse_id,user_id) VALUES <foreach collection='userIds' item='uid' separator=','>(#{warehouseId},#{uid})</foreach></script>") int insertWarehouseUsers(@Param("warehouseId") Long warehouseId,@Param("userIds") List<Long> userIds);
    @Select("SELECT u.id,u.username,u.real_name,u.job_title,u.team_id,u.workshop_id,u.status FROM sys_user u WHERE u.status='ENABLED' AND EXISTS(SELECT 1 FROM sys_user_role ur JOIN sys_role r ON r.id=ur.role_id WHERE ur.user_id=u.id AND r.role_code IN ('WAREHOUSE_ADMIN','ENGINEER')) ORDER BY u.real_name") List<UserSummaryVO> findWarehouseAssignableUsers();

    @Select("<script>SELECT p.id,p.spare_no,p.spare_name,p.specification,p.brand,p.unit,p.unit_price,p.supplier_id,s.supplier_name,p.compatible_model,p.lead_time_days,p.safety_days,p.status,p.created_at,p.updated_at FROM inv_spare_part p LEFT JOIN inv_supplier s ON s.id=p.supplier_id <where>1=1 <if test='q.keyword != null and q.keyword != &quot;&quot;'> AND (p.spare_no LIKE CONCAT('%',#{q.keyword},'%') OR p.spare_name LIKE CONCAT('%',#{q.keyword},'%') OR p.specification LIKE CONCAT('%',#{q.keyword},'%'))</if><if test='q.status != null and q.status != &quot;&quot;'> AND p.status=#{q.status}</if></where> ORDER BY p.id DESC LIMIT #{q.size} OFFSET #{q.offset}</script>") List<SparePartVO> findSparePartPage(@Param("q") SparePartQuery q);
    @Select("<script>SELECT COUNT(*) FROM inv_spare_part p <where>1=1 <if test='q.keyword != null and q.keyword != &quot;&quot;'> AND (p.spare_no LIKE CONCAT('%',#{q.keyword},'%') OR p.spare_name LIKE CONCAT('%',#{q.keyword},'%') OR p.specification LIKE CONCAT('%',#{q.keyword},'%'))</if><if test='q.status != null and q.status != &quot;&quot;'> AND p.status=#{q.status}</if></where></script>") long countSparePartPage(@Param("q") SparePartQuery q);
    @Select("SELECT id,spare_no,spare_name,specification,brand,unit,unit_price,supplier_id,compatible_model,lead_time_days,safety_days,status,created_at,updated_at FROM inv_spare_part WHERE id=#{id}") SparePart findSparePart(Long id);
    @Select("SELECT p.id,p.spare_no,p.spare_name,p.specification,p.brand,p.unit,p.unit_price,p.supplier_id,s.supplier_name,p.compatible_model,p.lead_time_days,p.safety_days,p.status,p.created_at,p.updated_at FROM inv_spare_part p LEFT JOIN inv_supplier s ON s.id=p.supplier_id WHERE p.id=#{id}") SparePartVO findSparePartVO(Long id);
    @Select("SELECT COUNT(*) FROM inv_spare_part WHERE spare_no=#{code} AND (#{excludeId} IS NULL OR id<>#{excludeId})") long countSparePartCode(@Param("code") String code,@Param("excludeId") Long excludeId);
    @Select("SELECT COUNT(*) FROM inv_supplier WHERE id=#{id} AND status='ENABLED'") long countEnabledSupplier(Long id);
    @Insert("INSERT INTO inv_spare_part(spare_no,spare_name,specification,brand,unit,unit_price,supplier_id,compatible_model,lead_time_days,safety_days,status) VALUES(#{spareNo},#{spareName},#{specification},#{brand},#{unit},#{unitPrice},#{supplierId},#{compatibleModel},#{leadTimeDays},#{safetyDays},#{status})") @Options(useGeneratedKeys=true,keyProperty="id") int insertSparePart(SparePart sparePart);
    @Update("UPDATE inv_spare_part SET spare_no=#{spareNo},spare_name=#{spareName},specification=#{specification},brand=#{brand},unit=#{unit},unit_price=#{unitPrice},supplier_id=#{supplierId},compatible_model=#{compatibleModel},lead_time_days=#{leadTimeDays},safety_days=#{safetyDays},status=#{status} WHERE id=#{id}") int updateSparePart(SparePart sparePart);
    @Select("SELECT id,supplier_no,supplier_name,status FROM inv_supplier WHERE status='ENABLED' ORDER BY supplier_name") List<SupplierVO> findSuppliers();

    @Select("<script>SELECT s.id,s.warehouse_id,w.warehouse_no,w.warehouse_name,s.spare_part_id,p.spare_no,p.spare_name,p.specification,p.unit,s.current_qty,ROUND(COALESCE(c.daily_qty,0)*p.safety_days,2) suggested_safety_stock,ROUND(COALESCE(c.daily_qty,0)*(p.lead_time_days+p.safety_days),2) reorder_point,CASE WHEN s.current_qty&lt;ROUND(COALESCE(c.daily_qty,0)*p.safety_days,2) THEN 'LOW' ELSE 'NORMAL' END stock_status,s.updated_at "+STOCK_FROM+STOCK_WHERE+" ORDER BY stock_status DESC,w.warehouse_name,p.spare_name LIMIT #{q.size} OFFSET #{q.offset}</script>") List<StockVO> findStockPage(@Param("q") StockQuery q,@Param("allData") boolean allData,@Param("warehouseIds") List<Long> warehouseIds);
    @Select("<script>SELECT COUNT(*) "+STOCK_FROM+STOCK_WHERE+"</script>") long countStockPage(@Param("q") StockQuery q,@Param("allData") boolean allData,@Param("warehouseIds") List<Long> warehouseIds);
    @Insert("INSERT INTO inv_stock(warehouse_id,spare_part_id,current_qty) VALUES(#{warehouseId},#{sparePartId},0) ON DUPLICATE KEY UPDATE id=id") int ensureStock(@Param("warehouseId") Long warehouseId,@Param("sparePartId") Long sparePartId);
    @Select("SELECT id,warehouse_id,spare_part_id,current_qty FROM inv_stock WHERE warehouse_id=#{warehouseId} AND spare_part_id=#{sparePartId} FOR UPDATE") StockRow lockStock(@Param("warehouseId") Long warehouseId,@Param("sparePartId") Long sparePartId);
    @Update("UPDATE inv_stock SET current_qty=#{qty} WHERE id=#{id}") int updateStock(@Param("id") Long id,@Param("qty") BigDecimal qty);

    @Insert("INSERT INTO inv_transaction(transaction_no,warehouse_id,spare_part_id,transaction_type,qty_change,qty_before,qty_after,unit_price,work_order_id,equipment_id,related_transaction_id,operator_id,remark) VALUES(#{transactionNo},#{warehouseId},#{sparePartId},#{transactionType},#{qtyChange},#{qtyBefore},#{qtyAfter},#{unitPrice},#{workOrderId},#{equipmentId},#{relatedTransactionId},#{operatorId},#{remark})") @Options(useGeneratedKeys=true,keyProperty="id") int insertTransaction(InventoryTransaction transaction);
    @Update("UPDATE inv_transaction SET related_transaction_id=#{relatedId} WHERE id=#{id}") int updateTransactionRelated(@Param("id") Long id,@Param("relatedId") Long relatedId);
    @Select("<script>SELECT t.id,t.transaction_no,t.warehouse_id,w.warehouse_name,t.spare_part_id,p.spare_no,p.spare_name,t.transaction_type,t.qty_change,t.qty_before,t.qty_after,t.unit_price,t.work_order_id,wo.work_order_no,t.equipment_id,e.equipment_no,t.related_transaction_id,t.operator_id,u.real_name operator_name,t.remark,t.created_at "+TX_FROM+TX_WHERE+" ORDER BY t.created_at DESC,t.id DESC LIMIT #{q.size} OFFSET #{q.offset}</script>") List<TransactionVO> findTransactionPage(@Param("q") TransactionQuery q,@Param("allData") boolean allData,@Param("warehouseIds") List<Long> warehouseIds);
    @Select("<script>SELECT COUNT(*) "+TX_FROM+TX_WHERE+"</script>") long countTransactionPage(@Param("q") TransactionQuery q,@Param("allData") boolean allData,@Param("warehouseIds") List<Long> warehouseIds);
    @Select("SELECT COALESCE(GREATEST(0,-SUM(qty_change)),0) FROM inv_transaction WHERE warehouse_id=#{warehouseId} AND spare_part_id=#{sparePartId} AND created_at>=DATE_SUB(NOW(),INTERVAL #{days} DAY) AND transaction_type IN ('OUTBOUND','ISSUE','RETURN','SCRAP')") BigDecimal sumNetOutbound(@Param("warehouseId") Long warehouseId,@Param("sparePartId") Long sparePartId,@Param("days") int days);

    @Insert("INSERT INTO inv_work_order_spare(work_order_id,warehouse_id,spare_part_id,qty,unit_price_snapshot,transaction_id,status,issued_by) VALUES(#{workOrderId},#{warehouseId},#{sparePartId},#{qty},#{unitPriceSnapshot},#{transactionId},#{status},#{issuedBy})") @Options(useGeneratedKeys=true,keyProperty="id") int insertWorkOrderSpare(WorkOrderSpare issue);
    @Select("SELECT id,work_order_id,warehouse_id,spare_part_id,qty,unit_price_snapshot,transaction_id,status,issued_by,issued_at FROM inv_work_order_spare WHERE id=#{id} FOR UPDATE") WorkOrderSpare lockWorkOrderSpare(Long id);
    @Select("SELECT COALESCE(SUM(qty_change),0) FROM inv_transaction WHERE related_transaction_id=#{issueTransactionId} AND transaction_type='RETURN'") BigDecimal sumReturned(Long issueTransactionId);
    @Update("UPDATE inv_work_order_spare SET status=#{status} WHERE id=#{id}") int updateIssueStatus(@Param("id") Long id,@Param("status") String status);
    @Select("SELECT i.id,i.work_order_id,i.warehouse_id,w.warehouse_no,w.warehouse_name,i.spare_part_id,p.spare_no,p.spare_name,p.specification,p.unit,i.qty issued_qty,COALESCE(SUM(CASE WHEN rt.transaction_type='RETURN' THEN rt.qty_change ELSE 0 END),0) returned_qty,i.qty-COALESCE(SUM(CASE WHEN rt.transaction_type='RETURN' THEN rt.qty_change ELSE 0 END),0) used_qty,i.unit_price_snapshot,i.status,i.issued_by,u.real_name issued_by_name,i.issued_at FROM inv_work_order_spare i JOIN inv_warehouse w ON w.id=i.warehouse_id JOIN inv_spare_part p ON p.id=i.spare_part_id LEFT JOIN inv_transaction rt ON rt.related_transaction_id=i.transaction_id LEFT JOIN sys_user u ON u.id=i.issued_by WHERE i.work_order_id=#{workOrderId} GROUP BY i.id,i.work_order_id,i.warehouse_id,w.warehouse_no,w.warehouse_name,i.spare_part_id,p.spare_no,p.spare_name,p.specification,p.unit,i.qty,i.unit_price_snapshot,i.status,i.issued_by,u.real_name,i.issued_at ORDER BY i.issued_at,i.id") List<WorkOrderSpareVO> findWorkOrderSpares(Long workOrderId);

    @Select("SELECT id FROM inv_warning WHERE warehouse_id=#{warehouseId} AND spare_part_id=#{sparePartId} AND status='OPEN' ORDER BY id DESC LIMIT 1 FOR UPDATE") Long findOpenWarning(@Param("warehouseId") Long warehouseId,@Param("sparePartId") Long sparePartId);
    @Insert("INSERT INTO inv_warning(warehouse_id,spare_part_id,warning_type,threshold_qty,current_qty,status) VALUES(#{warehouseId},#{sparePartId},'LOW_STOCK',#{threshold},#{current},'OPEN')") @Options(useGeneratedKeys=true,keyProperty="id") int insertWarning(WarningInsert warning);
    @Update("UPDATE inv_warning SET status='CLOSED',closed_at=NOW(),current_qty=#{current} WHERE id=#{id} AND status='OPEN'") int closeWarning(@Param("id") Long id,@Param("current") BigDecimal current);
    @Insert("INSERT INTO msg_notification(receiver_id,message_type,title,content,business_type,business_id,is_read) SELECT DISTINCT receiver_id,'STOCK_WARNING','低库存预警',#{content},'STOCK',#{warningId},0 FROM (SELECT user_id receiver_id FROM inv_warehouse_user WHERE warehouse_id=#{warehouseId} UNION SELECT ur.user_id FROM sys_user_role ur JOIN sys_role r ON r.id=ur.role_id WHERE r.role_code='MAINTENANCE_SUPERVISOR' AND r.status='ENABLED') x") int insertWarningMessages(@Param("warehouseId") Long warehouseId,@Param("warningId") Long warningId,@Param("content") String content);
    @Select("<script>SELECT v.id,v.warehouse_id,w.warehouse_name,v.spare_part_id,p.spare_no,p.spare_name,v.threshold_qty,v.current_qty,v.status,v.triggered_at,v.closed_at FROM inv_warning v JOIN inv_warehouse w ON w.id=v.warehouse_id JOIN inv_spare_part p ON p.id=v.spare_part_id WHERE v.status='OPEN' "+WARNING_SCOPE+" ORDER BY v.triggered_at DESC</script>") List<WarningVO> findOpenWarnings(@Param("allData") boolean allData,@Param("warehouseIds") List<Long> warehouseIds);

    record StockRow(Long id,Long warehouseId,Long sparePartId,BigDecimal currentQty) {}
    @lombok.Data class WarningInsert { private Long id; private Long warehouseId; private Long sparePartId; private BigDecimal threshold; private BigDecimal current; }
}
