<script setup lang="ts">
import { onMounted, reactive, shallowRef } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import * as api from '../../api/maintenance'
import * as equipmentApi from '../../api/equipment'
import { workOrderStatusLabel, workOrderStatusType } from '../../utils/workOrderStatus'

const loading=shallowRef(false),saving=shallowRef(false),records=shallowRef<any[]>([]),total=shallowRef(0),equipment=shallowRef<any[]>([]),history=shallowRef<any[]>([])
const query=reactive<any>({keyword:'',cycleType:null,status:null,page:1,size:10})
const dialog=reactive<any>({visible:false,editing:false,id:null,planNo:'',planName:'',equipmentId:null,cycleType:'MONTH',cycleValue:1,nextExecuteDate:'',runningHourThreshold:null})
const itemsDialog=reactive<any>({visible:false,plan:null,items:[]})
const historyDialog=reactive<any>({visible:false,plan:null})
const cycleLabels:any={WEEK:'周',MONTH:'月',QUARTER:'季度'}
function tomorrow(){const d=new Date();d.setDate(d.getDate()+1);return d.toISOString().slice(0,10)}
async function load(){loading.value=true;try{const r=await api.page(query);records.value=r.data.records;total.value=r.data.total}catch(e:any){ElMessage.error(e.response?.data?.message||'保养计划加载失败')}finally{loading.value=false}}
async function loadEquipment(){try{const r=await equipmentApi.page({page:1,size:100});equipment.value=r.data.records.filter((x:any)=>x.status!=='SCRAPPED')}catch{equipment.value=[]}}
function reset(){Object.assign(query,{keyword:'',cycleType:null,status:null,page:1,size:10});load()}
function openCreate(){Object.assign(dialog,{visible:true,editing:false,id:null,planNo:`PM-${Date.now().toString().slice(-8)}`,planName:'',equipmentId:null,cycleType:'MONTH',cycleValue:1,nextExecuteDate:tomorrow(),runningHourThreshold:null})}
async function openEdit(row:any){saving.value=true;try{const p=(await api.detail(row.id)).data;Object.assign(dialog,{visible:true,editing:true,id:p.id,planNo:p.planNo,planName:p.planName,equipmentId:p.equipmentId,cycleType:p.cycleType,cycleValue:p.cycleValue,nextExecuteDate:p.nextExecuteDate,runningHourThreshold:p.runningHourThreshold})}finally{saving.value=false}}
async function save(){if(!dialog.planNo.trim()||!dialog.planName.trim()||!dialog.equipmentId||!dialog.nextExecuteDate)return ElMessage.warning('请完整填写计划信息');saving.value=true;try{const payload={planNo:dialog.planNo,planName:dialog.planName,equipmentId:dialog.equipmentId,cycleType:dialog.cycleType,cycleValue:dialog.cycleValue,nextExecuteDate:dialog.nextExecuteDate,runningHourThreshold:dialog.runningHourThreshold};dialog.editing?await api.update(dialog.id,payload):await api.create(payload);ElMessage.success(dialog.editing?'计划已更新':'计划已创建，请继续配置检查项目');dialog.visible=false;await load()}catch(e:any){ElMessage.error(e.response?.data?.message||'保存失败')}finally{saving.value=false}}
async function toggle(row:any){try{await ElMessageBox.confirm(`确认${row.status==='ENABLED'?'停用':'启用'}计划“${row.planName}”？`,'计划状态',{type:'warning'});await api[row.status==='ENABLED'?'disable':'enable'](row.id);ElMessage.success('计划状态已更新');await load()}catch(e:any){if(e!=='cancel')ElMessage.error(e.response?.data?.message||'操作失败')}}
async function openItems(row:any){saving.value=true;try{const p=(await api.detail(row.id)).data;itemsDialog.plan=p;itemsDialog.items=(p.items||[]).map((x:any)=>({...x}));if(!itemsDialog.items.length)itemsDialog.items=[{itemName:'',standardDescription:'',sortNo:1,required:true}];itemsDialog.visible=true}finally{saving.value=false}}
function addItem(){itemsDialog.items.push({itemName:'',standardDescription:'',sortNo:itemsDialog.items.length+1,required:true})}
async function saveItems(){if(itemsDialog.items.some((x:any)=>!x.itemName.trim()))return ElMessage.warning('检查项目名称不能为空');saving.value=true;try{await api.saveItems(itemsDialog.plan.id,itemsDialog.items.map((x:any,i:number)=>({itemName:x.itemName,standardDescription:x.standardDescription,sortNo:i+1,required:x.required})));ElMessage.success('检查项目已保存');itemsDialog.visible=false;await load()}catch(e:any){ElMessage.error(e.response?.data?.message||'检查项目保存失败')}finally{saving.value=false}}
async function openHistory(row:any){saving.value=true;try{history.value=(await api.history(row.id)).data;historyDialog.plan=row;historyDialog.visible=true}finally{saving.value=false}}
async function scan(){saving.value=true;try{const r=(await api.scan()).data;ElMessage.success(`扫描完成：到期 ${r.due}，生成 ${r.generated}，跳过 ${r.skipped}，失败 ${r.failed}`);await load()}catch(e:any){ElMessage.error(e.response?.data?.message||'计划扫描失败')}finally{saving.value=false}}
onMounted(()=>{load();loadEquipment()})
</script>

<template><section class="module-page"><header class="module-header"><div><p class="eyebrow">PREVENTIVE MAINTENANCE</p><h1>预防性维护</h1><p>按日历周期安排检查任务，到期后自动进入统一工单流程。</p></div><div class="header-actions"><el-button v-permission="'maintenance:scan'" :loading="saving" @click="scan">立即检查到期计划</el-button><el-button v-permission="'maintenance:plan:add'" type="primary" @click="openCreate">新建保养计划</el-button></div></header>
<el-card shadow="never" class="filter-card"><el-form inline><el-form-item label="关键字"><el-input v-model="query.keyword" clearable placeholder="计划/设备" @keyup.enter="load"/></el-form-item><el-form-item label="周期"><el-select v-model="query.cycleType" clearable><el-option v-for="(label,key) in cycleLabels" :key="key" :label="label" :value="key"/></el-select></el-form-item><el-form-item label="状态"><el-select v-model="query.status" clearable><el-option label="启用" value="ENABLED"/><el-option label="停用" value="DISABLED"/></el-select></el-form-item><el-form-item class="filter-actions"><el-button type="primary" :loading="loading" @click="query.page=1;load()">查询</el-button><el-button @click="reset">重置</el-button></el-form-item></el-form></el-card>
<el-card shadow="never"><template #header><div class="card-title"><strong>保养计划</strong><small>下一执行日期到期后，每个计划只生成一张当前待办工单</small></div></template><el-table v-loading="loading" :data="records" stripe><template #empty><el-empty description="暂无保养计划，请先为设备制定周期计划" :image-size="72"/></template><el-table-column label="计划" min-width="190"><template #default="{row}"><span class="table-primary">{{row.planName}}</span><small class="table-subtitle">{{row.planNo}}</small></template></el-table-column><el-table-column label="设备" min-width="170"><template #default="{row}"><span>{{row.equipmentName}}</span><small class="table-subtitle">{{row.equipmentNo}} · {{row.workshopName}}</small></template></el-table-column><el-table-column label="周期" width="100"><template #default="{row}">每 {{row.cycleValue}} {{cycleLabels[row.cycleType]}}</template></el-table-column><el-table-column prop="nextExecuteDate" label="下次执行" width="120"/><el-table-column label="状态" width="82"><template #default="{row}"><el-tag :type="row.status==='ENABLED'?'success':'info'">{{row.status==='ENABLED'?'启用':'停用'}}</el-tag></template></el-table-column><el-table-column prop="lastGeneratedAt" label="最近生成" width="168"><template #default="{row}">{{row.lastGeneratedAt||'尚未生成'}}</template></el-table-column><el-table-column label="操作" width="260" fixed="right"><template #default="{row}"><el-button link type="primary" @click="openItems(row)">检查项目</el-button><el-button link @click="openHistory(row)">履历</el-button><el-button v-permission="'maintenance:plan:update'" link @click="openEdit(row)">编辑</el-button><el-button v-permission="'maintenance:plan:status'" link :type="row.status==='ENABLED'?'danger':'success'" @click="toggle(row)">{{row.status==='ENABLED'?'停用':'启用'}}</el-button></template></el-table-column></el-table><div class="pagination-row"><el-pagination v-model:current-page="query.page" v-model:page-size="query.size" :total="total" layout="total, sizes, prev, pager, next" @change="load"/></div></el-card>
<el-dialog v-model="dialog.visible" :title="dialog.editing?'编辑保养计划':'新建保养计划'" width="680px"><el-alert title="日历周期统一由后端计算；已生成的历史工单不会随计划修改而改变。" type="info" :closable="false"/><el-form class="maintenance-form" label-width="100px"><el-form-item label="计划编号" required><el-input v-model="dialog.planNo" maxlength="50"/></el-form-item><el-form-item label="计划名称" required><el-input v-model="dialog.planName" maxlength="100"/></el-form-item><el-form-item label="目标设备" required><el-select v-model="dialog.equipmentId" filterable style="width:100%"><el-option v-for="e in equipment" :key="e.id" :label="`${e.equipmentNo} · ${e.equipmentName}`" :value="e.id"/></el-select></el-form-item><el-form-item label="周期类型" required><el-select v-model="dialog.cycleType" style="width:100%"><el-option v-for="(label,key) in cycleLabels" :key="key" :label="label" :value="key"/></el-select></el-form-item><el-form-item label="周期倍数" required><el-input-number v-model="dialog.cycleValue" :min="1" :max="100" style="width:100%"/></el-form-item><el-form-item label="下次执行" required><el-date-picker v-model="dialog.nextExecuteDate" value-format="YYYY-MM-DD" type="date" style="width:100%"/></el-form-item><el-form-item label="小时阈值"><el-input-number v-model="dialog.runningHourThreshold" :min="0" :precision="2" placeholder="扩展条件，可不填" style="width:100%"/></el-form-item></el-form><template #footer><el-button @click="dialog.visible=false">取消</el-button><el-button type="primary" :loading="saving" @click="save">保存计划</el-button></template></el-dialog>
<el-dialog v-model="itemsDialog.visible" title="配置检查项目" width="820px"><el-alert :title="itemsDialog.plan?`${itemsDialog.plan.planNo} · ${itemsDialog.plan.planName}`:''" description="计划生成过工单后将锁定检查标准，以保证历史记录真实。" type="info" :closable="false"/><div class="item-editor"><div v-for="(item,index) in itemsDialog.items" :key="index" class="item-row"><span class="item-index">{{index+1}}</span><el-input v-model="item.itemName" placeholder="检查项目" maxlength="100"/><el-input v-model="item.standardDescription" placeholder="检查标准或要求" maxlength="500"/><el-checkbox v-model="item.required">必检</el-checkbox><el-button link type="danger" :disabled="itemsDialog.items.length===1" @click="itemsDialog.items.splice(index,1)">移除</el-button></div></div><el-button plain @click="addItem">添加检查项目</el-button><template #footer><el-button @click="itemsDialog.visible=false">取消</el-button><el-button type="primary" :loading="saving" @click="saveItems">保存检查项目</el-button></template></el-dialog>
<el-dialog v-model="historyDialog.visible" title="保养履历" width="860px"><el-table :data="history"><template #empty><el-empty description="该计划尚未生成保养工单"/></template><el-table-column prop="workOrderNo" label="工单编号" min-width="180"/><el-table-column label="状态" width="100"><template #default="{row}"><el-tag :type="workOrderStatusType(row.status)">{{workOrderStatusLabel(row.status)}}</el-tag></template></el-table-column><el-table-column prop="engineerName" label="工程师" width="110"><template #default="{row}">{{row.engineerName||'待派单'}}</template></el-table-column><el-table-column label="检查结果" width="130"><template #default="{row}">{{row.completedItems}} 项<span v-if="row.abnormalItems"> · {{row.abnormalItems}} 项异常</span></template></el-table-column><el-table-column prop="createdAt" label="生成时间" width="168"/><el-table-column prop="completedAt" label="完成时间" width="168"><template #default="{row}">{{row.completedAt||'-'}}</template></el-table-column></el-table></el-dialog></section></template>
