<script setup lang="ts">
import { onMounted, reactive, shallowRef } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { ElMessage, ElMessageBox } from 'element-plus'
import * as api from '../../api/knowledge'
import { useAuthStore } from '../../stores/auth'

const auth=useAuthStore();const route=useRoute();const router=useRouter();const loading=shallowRef(false);const rows=shallowRef<any[]>([]);const total=shallowRef(0);const detail=shallowRef<any>(null)
const query=reactive<any>({keyword:'',sourceWorkOrderNo:'',status:null,page:1,size:10})
const editor=reactive<any>({visible:false,id:null,title:'',faultSymptom:'',rootCause:'',solution:'',repairResult:''})
const statusMap:any={DRAFT:['草稿','info'],PENDING:['待审核','warning'],PUBLISHED:['已发布','success'],REJECTED:['已退回','danger']}
const statusLabel=(value:string)=>statusMap[value]?.[0]||value;const statusType=(value:string)=>statusMap[value]?.[1]||'info'
async function load(){loading.value=true;try{const response=await api.page(query);rows.value=response.data.records;total.value=response.data.total}catch(e:any){ElMessage.error(e.response?.data?.message||'知识列表加载失败')}finally{loading.value=false}}
async function openDetail(id:number){loading.value=true;try{detail.value=(await api.detail(id)).data}catch(e:any){ElMessage.error(e.response?.data?.message||'知识详情加载失败')}finally{loading.value=false}}
function openEdit(item:any){Object.assign(editor,{visible:true,id:item.id,title:item.title,faultSymptom:item.faultSymptom,rootCause:item.rootCause,solution:item.solution,repairResult:item.repairResult})}
async function save(){if(!editor.title.trim()||!editor.faultSymptom.trim()||!editor.rootCause.trim()||!editor.solution.trim()||!editor.repairResult.trim())return ElMessage.warning('请完整填写知识内容');loading.value=true;try{await api.update(editor.id,editor);ElMessage.success('知识草稿已保存');editor.visible=false;detail.value=null;await load()}catch(e:any){ElMessage.error(e.response?.data?.message||'保存失败')}finally{loading.value=false}}
async function submit(item:any){try{await ElMessageBox.confirm('提交后内容将锁定，等待主管审核。','提交知识审核',{type:'warning'});await api.submit(item.id);ElMessage.success('已提交主管审核');detail.value=null;await load()}catch(e:any){if(e!=='cancel')ElMessage.error(e.response?.data?.message||'提交失败')}}
async function review(item:any,approved:boolean){try{const {value}=await ElMessageBox.prompt(approved?'可填写审核意见':'请说明退回原因',approved?'审核通过':'审核退回',{inputPattern:approved?undefined:/\S+/,inputErrorMessage:'退回原因不能为空',type:approved?'success':'warning'});await api.review(item.id,{approved,remark:value});ElMessage.success(approved?'知识已正式发布':'知识已退回修改');detail.value=null;await load()}catch(e:any){if(e!=='cancel')ElMessage.error(e.response?.data?.message||'审核失败')}}
function reset(){Object.assign(query,{keyword:'',sourceWorkOrderNo:'',status:null,page:1});load()}
function canEdit(item:any){return ['DRAFT','REJECTED'].includes(item.status)&&auth.hasPermission('knowledge:update')}
function goWorkOrder(id:number){detail.value=null;router.push(`/work-orders/${id}`)}
onMounted(async()=>{await load();if(route.query.article)await openDetail(Number(route.query.article))})
</script>

<template><section class="module-page"><header class="module-header"><div><p class="eyebrow">MAINTENANCE KNOWLEDGE</p><h1>故障知识库</h1><p>从已完成维修工单沉淀经审核的现场经验，供后续维修参考。</p></div></header>
<el-alert title="正式知识均来自已完成维修工单并经过主管审核；历史经验仅供参考，不替代现场判断。" type="info" :closable="false"/>
<el-card shadow="never" class="filter-card"><el-form inline><el-form-item label="关键词"><el-input v-model="query.keyword" clearable placeholder="标题、现象、原因或方法" @keyup.enter="query.page=1;load()"/></el-form-item><el-form-item label="来源工单"><el-input v-model="query.sourceWorkOrderNo" clearable placeholder="工单编号"/></el-form-item><el-form-item label="状态"><el-select v-model="query.status" clearable placeholder="全部状态"><el-option label="草稿" value="DRAFT"/><el-option label="待审核" value="PENDING"/><el-option label="已发布" value="PUBLISHED"/><el-option label="已退回" value="REJECTED"/></el-select></el-form-item><el-form-item class="filter-actions"><el-button type="primary" @click="query.page=1;load()">查询</el-button><el-button @click="reset">重置</el-button></el-form-item></el-form></el-card>
<el-card shadow="never"><el-table v-loading="loading" :data="rows"><el-table-column label="知识条目" min-width="260"><template #default="{row}"><button class="knowledge-title" type="button" @click="openDetail(row.id)"><strong>{{row.title}}</strong><small>{{row.faultSymptom}}</small></button></template></el-table-column><el-table-column prop="equipmentTypeName" label="设备类型" width="130"/><el-table-column label="来源工单" min-width="175"><template #default="{row}"><el-button link type="primary" @click="goWorkOrder(row.sourceWorkOrderId)">{{row.sourceWorkOrderNo}}</el-button></template></el-table-column><el-table-column label="状态" width="95"><template #default="{row}"><el-tag :type="statusType(row.status)">{{statusLabel(row.status)}}</el-tag></template></el-table-column><el-table-column prop="submitterName" label="创建人" width="100"/><el-table-column prop="updatedAt" label="更新时间" width="168"/><el-table-column label="操作" width="210" fixed="right"><template #default="{row}"><el-button link type="primary" @click="openDetail(row.id)">详情</el-button><el-button v-if="canEdit(row)" link @click="openEdit(row)">编辑</el-button><el-button v-if="canEdit(row)&&auth.hasPermission('knowledge:submit')" link type="primary" @click="submit(row)">提交</el-button><template v-if="row.status==='PENDING'&&auth.hasPermission('knowledge:audit')"><el-button link type="success" @click="review(row,true)">通过</el-button><el-button link type="danger" @click="review(row,false)">退回</el-button></template></template></el-table-column></el-table><div class="pagination-row"><el-pagination v-model:current-page="query.page" v-model:page-size="query.size" :total="total" layout="total,prev,pager,next" @change="load"/></div></el-card>
<el-drawer v-model="detail" title="知识详情" size="min(760px, 92vw)" destroy-on-close><template v-if="detail"><div class="knowledge-detail-head"><div><el-tag :type="statusType(detail.status)">{{statusLabel(detail.status)}}</el-tag><h2>{{detail.title}}</h2><p>{{detail.equipmentTypeName}} · {{detail.equipmentNo}} {{detail.equipmentName}}</p></div><div class="header-actions"><el-button v-if="canEdit(detail)" @click="openEdit(detail)">编辑草稿</el-button><el-button v-if="canEdit(detail)&&auth.hasPermission('knowledge:submit')" type="primary" @click="submit(detail)">提交审核</el-button></div></div><div class="knowledge-sections"><article><small>故障现象</small><p>{{detail.faultSymptom}}</p></article><article><small>故障原因</small><p>{{detail.rootCause}}</p></article><article><small>解决方法</small><p>{{detail.solution}}</p></article><article><small>维修结果</small><p>{{detail.repairResult}}</p></article><article><small>实际使用备件</small><p>{{detail.spareSummary||'本次维修未使用备件'}}</p></article></div><el-descriptions :column="2" border><el-descriptions-item label="来源工单"><el-button link type="primary" @click="goWorkOrder(detail.sourceWorkOrderId)">{{detail.sourceWorkOrderNo}}</el-button></el-descriptions-item><el-descriptions-item label="创建人">{{detail.submitterName}}</el-descriptions-item><el-descriptions-item label="审核人">{{detail.reviewerName||'尚未审核'}}</el-descriptions-item><el-descriptions-item label="审核时间">{{detail.reviewedAt||'-'}}</el-descriptions-item><el-descriptions-item label="审核意见" :span="2">{{detail.reviewRemark||'-'}}</el-descriptions-item></el-descriptions><div v-if="detail.status==='PENDING'&&auth.hasPermission('knowledge:audit')" class="drawer-actions"><el-button type="success" @click="review(detail,true)">审核通过并发布</el-button><el-button type="danger" plain @click="review(detail,false)">退回修改</el-button></div></template></el-drawer>
<el-dialog v-model="editor.visible" title="编辑知识草稿" width="760px"><el-form label-position="top"><el-form-item label="知识标题" required><el-input v-model="editor.title" maxlength="200" show-word-limit/></el-form-item><el-form-item label="故障现象" required><el-input v-model="editor.faultSymptom" type="textarea" :rows="3"/></el-form-item><el-form-item label="故障原因" required><el-input v-model="editor.rootCause" type="textarea" :rows="3"/></el-form-item><el-form-item label="解决方法" required><el-input v-model="editor.solution" type="textarea" :rows="4"/></el-form-item><el-form-item label="维修结果" required><el-input v-model="editor.repairResult" type="textarea" :rows="3"/></el-form-item></el-form><template #footer><el-button @click="editor.visible=false">取消</el-button><el-button type="primary" :loading="loading" @click="save">保存草稿</el-button></template></el-dialog></section></template>
